# Generated by Django 6.0.4 on 2026-05-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_control", "0010_module_tier_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moduleaccesstier",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="rolemoduleaccess",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="roletemplate",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
