# Generated by Django 6.0.3 on 2026-04-07 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0006_staff_extended_fields"),
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="custom_field",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="JSON field for extensible data. Current supported fields: {'ifsc_code': 'string', 'allowance': 'decimal', 'deduction': 'decimal'}",
            ),
        ),
        migrations.CreateModel(
            name="StaffDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("resume", "Resume"),
                            ("joining_letter", "Joining Letter"),
                            ("tenth_certificate", "10th Certificate"),
                            ("eleventh_certificate", "11th Certificate"),
                            ("aadhar_card", "Aadhar Card"),
                            ("driving_license", "Driving License"),
                            ("other", "Other Document"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        help_text="S3 or file storage path", max_length=500
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                (
                    "file_size",
                    models.PositiveIntegerField(help_text="File size in bytes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_documents",
                        to="tenancy.school",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="hr.staff",
                    ),
                ),
            ],
            options={
                "db_table": "hr_staff_documents",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["staff", "document_type"],
                        name="hr_staff_do_staff_i_859b1a_idx",
                    ),
                    models.Index(
                        fields=["school", "created_at"],
                        name="hr_staff_do_school__34fe88_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("staff", "document_type", "file_name"),
                        name="uq_staff_doc_scope",
                    )
                ],
            },
        ),
    ]
