# Generated by Django 6.0.3 on 2026-04-07 09:38

import ast
import json

from django.db import migrations, models


def normalize_other_document_to_json(apps, schema_editor):
    Staff = apps.get_model("hr", "Staff")

    for staff in Staff.objects.only("id", "other_document").iterator():
        raw_value = staff.other_document

        if raw_value is None:
            normalized = "[]"
        elif isinstance(raw_value, str):
            text = raw_value.strip()
            if not text:
                normalized = "[]"
            else:
                parsed = None
                try:
                    parsed = json.loads(text)
                except Exception:
                    try:
                        parsed = ast.literal_eval(text)
                    except Exception:
                        parsed = [raw_value]
                normalized = json.dumps(parsed)
        else:
            normalized = json.dumps(raw_value)

        Staff.objects.filter(pk=staff.pk).update(other_document=normalized)


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0007_alter_staff_custom_field_staffdocument"),
    ]

    operations = [
        migrations.RunPython(normalize_other_document_to_json, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="staff",
            name="other_document",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
