# Generated by Django 6.0.3 on 2026-04-07 12:14

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_payroll_component_breakdown'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(blank=True, max_length=200)),
                ('school_url', models.URLField(blank=True, max_length=400)),
                ('logo_url', models.URLField(blank=True, max_length=400)),
                ('signature_url', models.URLField(blank=True, max_length=400)),
                ('default_allowance_items', models.JSONField(blank=True, default=list)),
                ('default_deduction_items', models.JSONField(blank=True, default=list)),
                ('default_allowance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('default_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_settings', to='tenancy.school')),
            ],
            options={
                'db_table': 'hr_payroll_settings',
            },
        ),
    ]
