# Generated by Django 6.0.3 on 2026-04-09 11:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0008_alter_staff_other_document"),
        ("hr", "0010_staffdocument"),
    ]

    operations = []
