# Generated by Django 6.0.4 on 2026-04-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0011_merge_20260409_1659"),
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="staffdocument",
            name="uq_staff_doc_scope",
        ),
        migrations.RemoveIndex(
            model_name="staffdocument",
            name="hr_staff_do_staff_i_859b1a_idx",
        ),
        migrations.RemoveIndex(
            model_name="staffdocument",
            name="hr_staff_do_school__34fe88_idx",
        ),
        migrations.AlterField(
            model_name="staffdocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("resume", "Resume"),
                    ("joining_letter", "Joining Letter"),
                    ("tenth_certificate", "Tenth Certificate"),
                    ("eleventh_certificate", "Eleventh Certificate"),
                    ("aadhar_card", "Aadhar Card"),
                    ("driving_license", "Driving License"),
                    ("other", "Other"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="staffdocument",
            name="file_path",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="staffdocument",
            name="file_size",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name="staffdocument",
            constraint=models.UniqueConstraint(
                fields=("school", "staff", "document_type", "file_name"),
                name="uq_hr_staff_document_scope",
            ),
        ),
    ]
