# Generated by Django 5.1.8 on 2026-05-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0017_designation_hierarchy_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="first_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="staff",
            name="last_name",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
