# Generated by Django 6.0 on 2026-06-09 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0022_staff_attendance_time_fields'),
    ]

    operations = [
    ]
