# Generated by Django 6.0 on 2026-06-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0023_add_personal_details_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='mother_tongue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='num_children',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='preferred_communication',
            field=models.CharField(blank=True, choices=[('mobile', 'Mobile'), ('whatsapp', 'WhatsApp'), ('personal_email', 'Personal Email'), ('official_email', 'Official Email')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='religion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
