# Generated by Django 6.0.4 on 2026-06-11 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0024_staff_blood_group_staff_mother_tongue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='short_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
