# Generated by Django 6.0.4 on 2026-06-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0025_department_short_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=255),
        ),
    ]
