# Generated by Django 6.0.4 on 2026-06-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0026_add_email_to_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=12),
        ),
        migrations.AddField(
            model_name='department',
            name='working_days',
            field=models.CharField(blank=True, choices=[('Monday - Friday', 'Monday - Friday'), ('Monday - Saturday', 'Monday - Saturday'), ('All 7 days', 'All 7 days')], default='Monday - Friday', max_length=30),
        ),
    ]
