# Generated by Django 5.1.8 on 2026-06-26 11:18

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0027_add_dept_status_working_days'),
        ('tenancy', '0018_schooltenant_school_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exit_type', models.CharField(choices=[('Resignation', 'Resignation'), ('Termination', 'Termination'), ('Retirement', 'Retirement'), ('End of Contract', 'End of Contract'), ('Transfer', 'Transfer'), ('Voluntary Exit', 'Voluntary Exit')], max_length=30)),
                ('exit_reason', models.TextField(blank=True)),
                ('last_working_day', models.DateField()),
                ('notice_period_status', models.CharField(blank=True, choices=[('Served', 'Served'), ('Bought Out', 'Bought Out'), ('Waived', 'Waived'), ('Partial', 'Partial')], max_length=20)),
                ('notice_period_days', models.PositiveIntegerField(blank=True, null=True)),
                ('exit_interview_conducted', models.CharField(choices=[('Pending', 'Pending'), ('Scheduled', 'Scheduled'), ('Conducted', 'Conducted'), ('Waived', 'Waived')], default='Pending', max_length=20)),
                ('exit_interview_notes', models.TextField(blank=True)),
                ('interview_date', models.DateField(blank=True, null=True)),
                ('primary_reason', models.TextField(blank=True)),
                ('handover_checklist', models.JSONField(blank=True, default=list)),
                ('financial_clearance', models.JSONField(blank=True, default=dict)),
                ('ff_status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Cleared', 'Cleared')], default='Pending', max_length=20)),
                ('salary_dues_cleared', models.BooleanField(default=False)),
                ('advance_loan', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('gratuity_applicable', models.BooleanField(default=False)),
                ('pf_esi_settlement', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('docs_to_issue', models.JSONField(blank=True, default=list)),
                ('hod_approval', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('principal_approval', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('hr_signoff', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('finance_clearance', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('hr_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='initiated', max_length=15)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offboarding_records', to='tenancy.school')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offboarding_records', to='hr.staff')),
            ],
            options={
                'db_table': 'hr_offboarding',
                'ordering': ['-created_at'],
            },
        ),
    ]
