# Generated by Django 5.1.8 on 2026-07-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0028_add_offboarding_set_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdocument',
            name='document_type',
            field=models.CharField(choices=[('resume', 'Resume'), ('joining_letter', 'Joining Letter'), ('tenth_certificate', 'Tenth Certificate'), ('eleventh_certificate', 'Eleventh Certificate'), ('aadhar_card', 'Aadhar Card'), ('driving_license', 'Driving License'), ('signature', 'Signature (scanned image)'), ('pan', 'PAN Card'), ('passport_photo', 'Passport-size photograph'), ('bank_proof', 'Bank cancelled cheque or passbook copy'), ('address_proof', 'Address proof'), ('degree', 'Degree / graduation certificate'), ('bed', 'B.Ed / D.El.Ed certificate'), ('experience', 'Experience letter (previous employer)'), ('noc', 'No-objection certificate (previous employer)'), ('medical_cert', 'Medical fitness certificate'), ('police_verification', 'Police verification certificate'), ('signed_onboarding_form', 'Signed Onboarding Acknowledgment'), ('other', 'Other')], max_length=32),
        ),
    ]
