# Generated by Django 5.1.8 on 2026-07-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0029_widen_gender_marital_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdocument',
            name='document_type',
            field=models.CharField(choices=[('resume', 'Resume'), ('joining_letter', 'Joining Letter'), ('tenth_certificate', 'Tenth Certificate'), ('eleventh_certificate', 'Eleventh Certificate'), ('aadhar_card', 'Aadhar Card'), ('driving_license', 'Driving License'), ('other', 'Other'), ('signature', 'Signature'), ('pan_card', 'PAN Card'), ('passport_photo', 'Passport Photo'), ('bank_proof', 'Bank Proof'), ('address_proof', 'Address Proof'), ('twelfth_certificate', 'Twelfth Certificate'), ('degree_certificate', 'Degree Certificate'), ('bed_certificate', 'B.Ed / D.El.Ed Certificate'), ('experience_letter', 'Experience Letter'), ('noc_certificate', 'No-Objection Certificate'), ('medical_fitness_certificate', 'Medical Fitness Certificate'), ('police_verification_certificate', 'Police Verification Certificate')], max_length=40),
        ),
    ]
