# Generated by Django 5.1.8 on 2026-07-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0029_alter_staffdocument_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='applicable_departments',
            field=models.JSONField(blank=True, default=list, help_text='Department names/IDs this leave type applies to; empty = all'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='applicable_designations',
            field=models.JSONField(blank=True, default=list, help_text='Designation names/IDs this leave type applies to; empty = all'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='attachment_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='can_carry_forward',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='carry_forward_expiry_days',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 = carried-forward days never expire'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='carry_forward_type',
            field=models.CharField(choices=[('limited', 'Limited'), ('unlimited', 'Unlimited')], default='limited', max_length=16),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='max_carry_forward_days',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='medical_certificate_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='minimum_notice_period',
            field=models.PositiveSmallIntegerField(default=0, help_text="Minimum days' notice required before this leave can be applied for"),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='minimum_service_period',
            field=models.PositiveSmallIntegerField(default=0, help_text='Minimum months of service required before staff can use this leave type'),
        ),
    ]
