# Generated by Django 5.1.8 on 2026-07-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0030_leavetype_applicable_departments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='allow_backdated_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='allow_future_leave',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='allow_half_day',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='allow_leave_cancellation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='allow_leave_combination',
            field=models.BooleanField(default=True, help_text='Allow combining with other leave types in one continuous stretch'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='allow_leave_extension',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='allow_negative_balance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='allow_notice_period_leave',
            field=models.BooleanField(default=True, help_text='Allow staff serving notice period to use this leave type'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='allow_probation_leave',
            field=models.BooleanField(default=False, help_text='Allow staff on probation to use this leave type'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='applicable_employment_types',
            field=models.JSONField(blank=True, default=list, help_text='Staff.contract_type values this leave type applies to (e.g. permanent, contract); empty = all'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='applicable_gender',
            field=models.CharField(choices=[('all', 'All'), ('male', 'Male'), ('female', 'Female')], default='all', max_length=16),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='cancellation_allowed_until',
            field=models.PositiveSmallIntegerField(default=0, help_text='Days after leave start within which cancellation is allowed; 0 = anytime'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='carry_forward_mode',
            field=models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default='automatic', max_length=16),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='convert_to_lop',
            field=models.BooleanField(default=True, help_text='Convert to Loss of Pay when balance is exhausted (if allow_negative_balance is off)'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='count_holidays_as_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='count_weekoffs_as_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='maximum_backdated_days',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='maximum_consecutive_days',
            field=models.PositiveSmallIntegerField(default=0, help_text='Maximum consecutive days allowed; 0 = no limit'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='maximum_future_days',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 = no limit on how far in advance leave can be applied'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='maximum_leave_duration',
            field=models.PositiveSmallIntegerField(default=0, help_text='Maximum days per request; 0 = no maximum'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='medical_certificate_after_days',
            field=models.PositiveSmallIntegerField(default=0, help_text='Medical certificate required if leave exceeds this many consecutive days; 0 = always required when medical_certificate_required is set'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='minimum_leave_duration',
            field=models.PositiveSmallIntegerField(default=0, help_text='Minimum days per request; 0 = no minimum'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='policy_note',
            field=models.TextField(blank=True, help_text='Free-text note shown to staff alongside this policy'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='sandwich_leave_enabled',
            field=models.BooleanField(default=False, help_text='Count intervening holidays/week-offs as leave when leave is taken on both sides of them'),
        ),
    ]
