# Generated by Django 5.1.8 on 2026-07-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0031_leavetype_allow_backdated_leave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='is_builtin',
            field=models.BooleanField(default=False),
        ),
    ]
