# Generated by Django 5.1.8 on 2026-08-03 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0032_leavetype_is_builtin'),
        ('tenancy', '0021_schooltenant_geofence_radius_meters_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='staffonboarddocument',
            name='uq_hr_onboard_doc_user_key',
        ),
        migrations.AddField(
            model_name='staffonboarddocument',
            name='related_staff',
            field=models.ForeignKey(blank=True, help_text='Set while editing an existing staff member; null while onboarding a brand-new hire.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboard_documents_pending', to='hr.staff'),
        ),
        migrations.AddConstraint(
            model_name='staffonboarddocument',
            constraint=models.UniqueConstraint(fields=('uploaded_by', 'doc_key', 'related_staff'), name='uq_hr_onboard_doc_user_key_staff'),
        ),
    ]
