# Generated by Django 5.1.8 on 2026-08-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0033_remove_staffonboarddocument_uq_hr_onboard_doc_user_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='custom_field',
            field=models.JSONField(blank=True, default=dict, help_text="JSON field for extensible data. Current supported fields: {'ifsc_code': 'string', 'bank_city': 'string', 'bank_state': 'string', 'allowance': 'decimal', 'deduction': 'decimal', 'hra': 'decimal', 'da': 'decimal', 'travel_allowance': 'decimal', 'medical_allowance': 'decimal', 'special_allowance': 'decimal', 'custom_earnings': [{'label': 'string', 'amount': 'decimal'}], 'custom_deductions': [{'label': 'string', 'amount': 'decimal'}]}"),
        ),
    ]
