# Generated by Django 6.0.4 on 2026-08-31 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0036_leaverequest_applied_by_leaverequest_half_day_type_and_more'),
        ('tenancy', '0022_alter_domain_domain_alter_domain_is_primary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='absence_type',
            field=models.CharField(blank=True, choices=[('emergency', 'Emergency'), ('unplanned', 'Unplanned'), ('retroactive', 'Retroactive')], max_length=12),
        ),
        migrations.CreateModel(
            name='ApprovalChainPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l1_approver_role', models.CharField(choices=[('HOD', 'HOD'), ('Principal', 'Principal'), ('Vice Principal', 'Vice Principal'), ('HR Admin', 'HR Admin'), ('', '—')], default='HOD', max_length=20)),
                ('l2_approver_role', models.CharField(blank=True, choices=[('HOD', 'HOD'), ('Principal', 'Principal'), ('Vice Principal', 'Vice Principal'), ('HR Admin', 'HR Admin'), ('', '—')], default='', max_length=20)),
                ('l2_trigger_days', models.PositiveSmallIntegerField(default=0, help_text='Leave duration (days) at/above which L2 approval is also required. 0 = never.')),
                ('response_window_days', models.PositiveSmallIntegerField(default=2, help_text="Days an approver has to act before the request is flagged 'stuck in chain'.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('designation', models.ForeignKey(blank=True, help_text="Null = the default 'All Staff' policy.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_chain_policies', to='hr.designation')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_chain_policies', to='tenancy.school')),
            ],
            options={
                'db_table': 'hr_approval_chain_policies',
                'ordering': ['designation_id'],
                'constraints': [models.UniqueConstraint(fields=('school', 'designation'), name='uq_hr_chain_policy_scope')],
            },
        ),
        migrations.CreateModel(
            name='LeaveApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField()),
                ('role_label', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('response_window_days', models.PositiveSmallIntegerField(default=2)),
                ('became_active_at', models.DateTimeField()),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_approval_steps', to=settings.AUTH_USER_MODEL)),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='hr.leaverequest')),
            ],
            options={
                'db_table': 'hr_leave_approval_steps',
                'ordering': ['leave_request_id', 'sequence'],
                'constraints': [models.UniqueConstraint(fields=('leave_request', 'sequence'), name='uq_hr_leave_step_seq')],
            },
        ),
    ]
