# Generated by Django 5.1.8 on 2026-09-01 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0016_seed_approval_chain_permission'),
        ('core', '0028_levelscheduleconfig'),
        ('hr', '0037_leaverequest_absence_type_approvalchainpolicy_and_more'),
        ('students', '0026_student_aadhaar_no_student_abc_id_and_more'),
        ('tenancy', '0022_alter_domain_domain_alter_domain_is_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavedefine',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_defines', to='core.academicyear'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='is_govt_mandated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='max_encashment_days',
            field=models.PositiveSmallIntegerField(default=0, help_text='Max unused days that can be encashed (paid out) per year; 0 = not encashable'),
        ),
        migrations.AddIndex(
            model_name='leavedefine',
            index=models.Index(fields=['school', 'academic_year', 'leave_type'], name='idx_hr_ld_sch_ay_lt'),
        ),
        migrations.AddConstraint(
            model_name='leavedefine',
            constraint=models.UniqueConstraint(condition=models.Q(('role__isnull', False), ('school_class__isnull', True), ('section__isnull', True), ('staff__isnull', True), ('student__isnull', True)), fields=('school', 'academic_year', 'leave_type', 'role'), name='uq_hr_ld_role_entitlement_scope'),
        ),
        migrations.AddConstraint(
            model_name='leavedefine',
            constraint=models.UniqueConstraint(condition=models.Q(('role__isnull', True), ('school_class__isnull', True), ('section__isnull', True), ('staff__isnull', True), ('student__isnull', True)), fields=('school', 'academic_year', 'leave_type'), name='uq_hr_ld_all_staff_entitlement_scope'),
        ),
    ]
