# Generated by Django 5.1.8 on 2026-09-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0038_leave_type_govt_encash_leavedefine_ay'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='substitute_staff_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
