# Generated by Django 6.0.4 on 2026-09-01 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_control", "0016_seed_approval_chain_permission"),
        ("hr", "0039_leaverequest_substitute_staff_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvalchainpolicy",
            name="l1_approver_role",
            field=models.ForeignKey(
                blank=True,
                help_text="Role whose holder (matched by Designation name) approves at L1.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="access_control.role",
            ),
        ),
        migrations.AlterField(
            model_name="approvalchainpolicy",
            name="l2_approver_role",
            field=models.ForeignKey(
                blank=True,
                help_text="Role whose holder approves at L2, once l2_trigger_days is met. Blank = no L2 step.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="access_control.role",
            ),
        ),
        migrations.AlterField(
            model_name="leaveapprovalstep",
            name="role_label",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
