# Generated by Django 5.1.8 on 2026-09-02 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0016_seed_approval_chain_permission'),
        ('hr', '0040_alter_approvalchainpolicy_l1_approver_role_and_more'),
        ('tenancy', '0022_alter_domain_domain_alter_domain_is_primary'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='approvalchainpolicy',
            name='uq_hr_chain_policy_scope',
        ),
        migrations.AddField(
            model_name='approvalchainpolicy',
            name='department',
            field=models.ForeignKey(blank=True, help_text="Null = applies regardless of department. A (designation, department) match beats (designation, any department), which beats (any designation, department), which beats the (null, null) 'All Staff' default.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_chain_policies', to='hr.department'),
        ),
        migrations.AddField(
            model_name='approvalchainpolicy',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive rules are skipped during matching.'),
        ),
        migrations.AddField(
            model_name='staff',
            name='reporting_manager',
            field=models.ForeignKey(blank=True, help_text='Who this staff member reports to. Used as the leave-approval L1 (and their manager as L2) in preference to the designation/role-based Approval Chain policy.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='hr.staff'),
        ),
        migrations.AlterField(
            model_name='approvalchainpolicy',
            name='designation',
            field=models.ForeignKey(blank=True, help_text='Null = applies regardless of designation.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_chain_policies', to='hr.designation'),
        ),
        migrations.AlterField(
            model_name='approvalchainpolicy',
            name='l1_approver_role',
            field=models.ForeignKey(blank=True, help_text='Role whose holder (matched by Designation name) approves at L1. Only used when the applicant has no Reporting Manager set — see Staff.reporting_manager.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='access_control.role'),
        ),
        migrations.AddConstraint(
            model_name='approvalchainpolicy',
            constraint=models.UniqueConstraint(fields=('school', 'designation', 'department'), name='uq_hr_chain_policy_scope'),
        ),
    ]
