# Generated by Django 5.1.8 on 2026-09-03 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0041_remove_approvalchainpolicy_uq_hr_chain_policy_scope_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapprovalstep',
            name='acted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_approval_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='approved_via_admin_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='leaveapprovalstep',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('bypassed', 'Bypassed by Admin')], default='pending', max_length=10),
        ),
    ]
