# Generated by Django 5.1.8 on 2026-08-21 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancy", "0021_schooltenant_geofence_radius_meters_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BotQueryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.TextField()),
                ("resolver_type", models.CharField(max_length=40)),
                (
                    "resolved_intent_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bot_query_logs",
                        to="tenancy.school",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bot_query_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "assistant_bot_query_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["school", "created_at"],
                        name="assistant_b_school__d5a3c3_idx",
                    ),
                    models.Index(
                        fields=["resolver_type"], name="assistant_b_resolve_268c48_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FAQEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic_key", models.SlugField(max_length=60)),
                (
                    "keywords",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Phrases/regex-free substrings that trigger this topic.",
                    ),
                ),
                ("answer", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faq_entries",
                        to="tenancy.school",
                    ),
                ),
            ],
            options={
                "db_table": "assistant_faq_entries",
                "ordering": ["topic_key"],
                "indexes": [
                    models.Index(
                        fields=["school", "is_active"],
                        name="assistant_f_school__42e42e_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("school", "topic_key"), name="uq_faq_entry_school_topic"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topic_key",
                    models.CharField(
                        choices=[
                            ("fee", "Fee reminder"),
                            ("attendance", "Attendance concern"),
                            ("exam", "Exam/result notice"),
                            ("meeting", "Parent-teacher meeting"),
                            ("generic", "Generic notice"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Use {topic}, {date}, {time}, {venue}, {rsvp_date} as placeholders."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_templates",
                        to="tenancy.school",
                    ),
                ),
            ],
            options={
                "db_table": "assistant_message_templates",
                "ordering": ["topic_key"],
                "indexes": [
                    models.Index(
                        fields=["school", "is_active"],
                        name="assistant_m_school__48b098_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("school", "topic_key"),
                        name="uq_msg_template_school_topic",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PersonalCalendarEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "week_start_date",
                    models.DateField(help_text="Monday of the target week."),
                ),
                (
                    "day_index",
                    models.PositiveSmallIntegerField(help_text="0=Monday .. 6=Sunday"),
                ),
                ("time", models.CharField(help_text="HH:MM, 24-hour.", max_length=5)),
                ("title", models.CharField(max_length=255)),
                ("category", models.CharField(default="meeting", max_length=30)),
                ("ai_generated", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_events",
                        to="tenancy.school",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "assistant_personal_calendar_events",
                "ordering": ["week_start_date", "day_index", "time"],
                "indexes": [
                    models.Index(
                        fields=["school", "user", "week_start_date"],
                        name="assistant_p_school__537b45_idx",
                    )
                ],
            },
        ),
    ]
