# Generated by Django 5.1.8 on 2026-08-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0002_seed_global_defaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalcalendarevent",
            name="done",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="personalcalendarevent",
            name="note",
            field=models.TextField(blank=True, default=""),
        ),
    ]
