# Generated by Django 6.0.3 on 2026-04-07 05:37

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0005_extend_studentattendance_audit_lock"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="studentattendance",
            new_name="student_att_student_10af52_idx",
            old_name="attendance_s_student_idx",
        ),
        migrations.RenameIndex(
            model_name="studentattendance",
            new_name="student_att_class_i_4e4bf0_idx",
            old_name="attendance_s_class_id_idx",
        ),
        migrations.RenameIndex(
            model_name="studentattendance",
            new_name="student_att_section_b5a24d_idx",
            old_name="attendance_s_section_idx",
        ),
        migrations.RenameIndex(
            model_name="studentattendance",
            new_name="student_att_attenda_4f37fb_idx",
            old_name="attendance_s_attendan_idx",
        ),
        migrations.AlterField(
            model_name="studentattendance",
            name="marked_at",
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
    ]
