# Generated by Django 5.1.8 on 2026-07-27 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_holiday_calendar'),
        ('tenancy', '0019_schooltenant_school'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.CharField(blank=True, max_length=32)),
                ('message', models.TextField()),
                ('audience_type', models.CharField(choices=[('all_parents', 'All Parents'), ('class_parents', 'Class Parents'), ('teachers', 'Teachers'), ('all_staff', 'All Staff')], max_length=20)),
                ('audience_class_ids', models.JSONField(blank=True, default=list)),
                ('channels', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('sent', 'Sent'), ('failed', 'Failed')], default='scheduled', max_length=12)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_count', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcast_messages', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_messages', to='tenancy.school')),
            ],
            options={
                'db_table': 'communication_broadcast_messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
