# Generated by Django 5.1.8 on 2026-05-15 12:30
# NOTE: This migration was from an early django-tenants-based approach.
# Migration 0003_remove_domain_tenant_delete_client_delete_domain immediately
# removes the models created here. The django_tenants import is guarded so
# migration loading works even when the module path isn't fully resolvable
# at import time (e.g. when Django settings aren't yet configured).

import django.db.models.deletion
from django.db import migrations, models

try:
    import django_tenants.postgresql_backend.base as _dt_base
    _check_schema_name = _dt_base._check_schema_name
except Exception:
    # Fallback validator: accept any value; the real check runs at runtime.
    def _check_schema_name(value):
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schema_name",
                    models.CharField(
                        db_index=True,
                        max_length=63,
                        unique=True,
                        validators=[
                            _check_schema_name
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("tnt_id", models.CharField(max_length=20, unique=True)),
                ("campus", models.CharField(blank=True, max_length=200)),
                ("board", models.CharField(blank=True, max_length=30)),
                ("state_code", models.CharField(blank=True, max_length=2)),
                ("state_name", models.CharField(blank=True, max_length=100)),
                ("plan", models.CharField(default="Standard", max_length=30)),
                ("students_count", models.PositiveIntegerField(default=0)),
                ("staff_count", models.PositiveIntegerField(default=0)),
                ("seats", models.PositiveIntegerField(default=500)),
                ("status", models.CharField(default="active", max_length=20)),
                ("gstin", models.CharField(blank=True, max_length=15)),
                ("pan", models.CharField(blank=True, max_length=10)),
                ("affiliation", models.CharField(blank=True, max_length=50)),
                ("udise", models.CharField(blank=True, max_length=11)),
                ("mrr", models.PositiveIntegerField(default=0)),
                ("created_on", models.DateField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(db_index=True, max_length=253, unique=True),
                ),
                ("is_primary", models.BooleanField(db_index=True, default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="tenancy.client",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
