# Generated by Django 5.1.8 on 2026-05-18 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0002_client_domain"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="domain",
            name="tenant",
        ),
        migrations.DeleteModel(
            name="Client",
        ),
        migrations.DeleteModel(
            name="Domain",
        ),
    ]
