# Generated by Django 6.0.3 on 2026-05-13 06:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenancy", "0003_add_tenant_audit_log"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="tenantauditlog",
            new_name="tenancy_aud_tenant__1a2506_idx",
            old_name="tenancy_aud_tenant__idx",
        ),
        migrations.RenameIndex(
            model_name="tenantauditlog",
            new_name="tenancy_aud_schema__e284c3_idx",
            old_name="tenancy_aud_schema__idx",
        ),
        migrations.RenameIndex(
            model_name="tenantauditlog",
            new_name="tenancy_aud_action_cb18da_idx",
            old_name="tenancy_aud_action_idx",
        ),
        migrations.RenameIndex(
            model_name="tenantauditlog",
            new_name="tenancy_aud_status_93b94e_idx",
            old_name="tenancy_aud_status_idx",
        ),
    ]
