# Generated by Django 5.2.12 on 2026-05-15 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenancy", "0005_super_admin_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("academic", "Academic"),
                            ("finance", "Finance & Fees"),
                            ("attendance", "Attendance"),
                            ("behaviour", "Behaviour"),
                            ("library", "Library"),
                            ("transport", "Transport"),
                            ("inventory", "Inventory"),
                            ("hr", "HR"),
                            ("communication", "Communication"),
                            ("analytics", "Analytics"),
                            ("api", "API"),
                            ("admin", "Admin"),
                            ("integration", "Integration"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                ("enabled_by_default", models.BooleanField(default=False)),
                ("depends_on", models.CharField(blank=True, max_length=512)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "tenant_features",
            },
        ),
        migrations.CreateModel(
            name="TenantFeatureAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=32)),
                (
                    "feature_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("feature_enabled", "Feature Enabled"),
                            ("feature_disabled", "Feature Disabled"),
                            ("feature_override_set", "Override Set"),
                            ("feature_override_cleared", "Override Cleared"),
                            ("plan_changed", "Plan Changed"),
                            ("plan_updated", "Plan Updated"),
                            ("rate_limit_changed", "Rate Limit Changed"),
                            ("tenant_suspended", "Tenant Suspended"),
                            ("tenant_activated", "Tenant Activated"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("actor_user_id", models.IntegerField(blank=True, null=True)),
                ("actor_username", models.CharField(blank=True, max_length=256)),
                ("actor_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("old_value", models.JSONField(blank=True, null=True)),
                ("new_value", models.JSONField(blank=True, null=True)),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "tenant_feature_audit",
            },
        ),
        migrations.CreateModel(
            name="TenantFeatureFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        blank=True,
                        help_text="Null = use plan default, True/False = override",
                        null=True,
                    ),
                ),
                ("config_override", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "changed_by",
                    models.CharField(
                        blank=True,
                        help_text="User/system that made the change",
                        max_length=256,
                    ),
                ),
            ],
            options={
                "db_table": "tenant_feature_flags",
            },
        ),
        migrations.CreateModel(
            name="TenantMigrationAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school_id", models.IntegerField(db_index=True)),
                (
                    "tenant_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=32, null=True
                    ),
                ),
                (
                    "schema_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("rolled_back", "Rolled Back"),
                            ("validated", "Validated"),
                        ],
                        db_index=True,
                        default="started",
                        max_length=24,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "checkpoint",
                    models.CharField(
                        blank=True,
                        help_text="Last completed table or step",
                        max_length=256,
                    ),
                ),
                ("tables", models.JSONField(blank=True, default=dict)),
                ("validation", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True, null=True)),
                ("actor_user_id", models.IntegerField(blank=True, null=True)),
                ("actor_username", models.CharField(blank=True, max_length=256)),
                ("actor_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "tenant_migration_audit",
            },
        ),
        migrations.CreateModel(
            name="TenantPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan_id",
                    models.CharField(db_index=True, max_length=32, unique=True),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("trial", "Trial"),
                            ("premium", "Premium"),
                            ("enterprise", "Enterprise"),
                            ("custom", "Custom"),
                        ],
                        max_length=32,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                (
                    "features",
                    models.JSONField(
                        default=dict,
                        help_text="Dict of feature flags and their default values",
                    ),
                ),
                ("api_rate_limit_per_minute", models.IntegerField(default=100)),
                ("api_rate_limit_per_hour", models.IntegerField(default=10000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "tenant_plans",
            },
        ),
        migrations.RenameIndex(
            model_name="superadminfeaturetoggle",
            new_name="super_admin_tenant__668d54_idx",
            old_name="super_admin_tenant__a86e50_idx",
        ),
        migrations.RenameIndex(
            model_name="superadmininvoice",
            new_name="super_admin_status_ccbdc6_idx",
            old_name="super_admin_status_f4f82c_idx",
        ),
        migrations.RenameIndex(
            model_name="superadmininvoice",
            new_name="super_admin_invoice_13afee_idx",
            old_name="super_admin_invoice_8b4047_idx",
        ),
        migrations.AddIndex(
            model_name="tenantfeature",
            index=models.Index(
                fields=["category"], name="tenant_feat_categor_a6fe24_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tenantfeature",
            index=models.Index(
                fields=["feature_id"], name="tenant_feat_feature_3c30c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tenantfeatureaudit",
            index=models.Index(
                fields=["tenant_id", "created_at"],
                name="tenant_feat_tenant__356a1f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tenantfeatureaudit",
            index=models.Index(
                fields=["feature_id", "created_at"],
                name="tenant_feat_feature_7f6bbd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tenantfeatureaudit",
            index=models.Index(
                fields=["action", "created_at"], name="tenant_feat_action_054448_idx"
            ),
        ),
        migrations.AddField(
            model_name="tenantfeatureflag",
            name="feature",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tenant_flags",
                to="tenancy.tenantfeature",
            ),
        ),
        migrations.AddField(
            model_name="tenantfeatureflag",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feature_flags",
                to="tenancy.schooltenant",
            ),
        ),
        migrations.AddIndex(
            model_name="tenantmigrationaudit",
            index=models.Index(
                fields=["school_id", "started_at"],
                name="tenant_migr_school__a5731e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tenantmigrationaudit",
            index=models.Index(
                fields=["tenant_id", "started_at"],
                name="tenant_migr_tenant__aa3a5f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tenantmigrationaudit",
            index=models.Index(
                fields=["status", "started_at"], name="tenant_migr_status_5c5dda_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tenantplan",
            index=models.Index(
                fields=["plan_type"], name="tenant_plan_plan_ty_f3e559_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tenantfeatureflag",
            index=models.Index(
                fields=["tenant", "feature"], name="tenant_feat_tenant__855492_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tenantfeatureflag",
            index=models.Index(
                fields=["is_enabled"], name="tenant_feat_is_enab_866d84_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tenantfeatureflag",
            unique_together={("tenant", "feature")},
        ),
    ]
