# Generated by Django 5.2.12 on 2026-05-20 07:45

import uuid
from django.db import migrations, models


SEED_PLANS = [
    {
        "code": "starter",
        "name": "Starter",
        "price_inr": "4500.00",
        "billing_cycle": "monthly",
        "popular": False,
        "sort_order": 10,
        "description": "For small schools getting started.",
        "features": [
            "Up to 200 students",
            "Core admissions & attendance",
            "Email support",
            "1 GB document storage",
        ],
    },
    {
        "code": "standard",
        "name": "Standard",
        "price_inr": "9000.00",
        "billing_cycle": "monthly",
        "popular": False,
        "sort_order": 20,
        "description": "Most common pick for growing schools.",
        "features": [
            "Up to 800 students",
            "Academics, fees & exams",
            "Parent portal & SMS",
            "10 GB document storage",
        ],
    },
    {
        "code": "premium",
        "name": "Premium",
        "price_inr": "19500.00",
        "billing_cycle": "monthly",
        "popular": True,
        "sort_order": 30,
        "description": "Full suite for established schools.",
        "features": [
            "Up to 2,500 students",
            "All Standard features",
            "Transport & hostel modules",
            "Priority support",
            "50 GB document storage",
        ],
    },
    {
        "code": "enterprise",
        "name": "Enterprise",
        "price_inr": "34500.00",
        "billing_cycle": "monthly",
        "popular": False,
        "sort_order": 40,
        "description": "Multi-campus and custom deployments.",
        "features": [
            "Unlimited students",
            "All Premium features",
            "Dedicated success manager",
            "SSO & custom integrations",
            "Unlimited storage",
        ],
    },
]


def seed_plans(apps, schema_editor):
    SubscriptionPlan = apps.get_model("tenancy", "SubscriptionPlan")
    for data in SEED_PLANS:
        SubscriptionPlan.objects.update_or_create(
            code=data["code"], defaults=data
        )


def unseed_plans(apps, schema_editor):
    SubscriptionPlan = apps.get_model("tenancy", "SubscriptionPlan")
    SubscriptionPlan.objects.filter(
        code__in=[p["code"] for p in SEED_PLANS]
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("tenancy", "0007_add_branding_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.SlugField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                ("price_inr", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                        default="monthly",
                        max_length=16,
                    ),
                ),
                ("popular", models.BooleanField(default=False)),
                ("features", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "subscription_plans",
                "ordering": ["sort_order", "price_inr", "name"],
            },
        ),
        migrations.RunPython(seed_plans, unseed_plans),
    ]
