# Generated by Django 6.0.4 on 2026-05-20 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0003_remove_domain_tenant_delete_client_delete_domain"),
        ("tenancy", "0008_add_subscription_plan"),
    ]

    operations = []
