# Generated by Django 6.0.4 on 2026-05-21 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0009_merge_20260520_1700"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="tenant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="domains",
                to="tenancy.schooltenant",
            ),
            preserve_default=False,
        ),
    ]
