# Generated by Django 6.0.4 on 2026-05-21 11:55
#
# FIXED 2026-08-18: this migration originally contained only an AddField
# for `tenant`, on the assumption that a `Domain` model already existed in
# state. It didn't — migration 0003_remove_domain_tenant_delete_client_delete_domain
# (an earlier, unrelated Client/Domain concept) deleted the model that
# once existed, and nothing ever recreated it before this file tried to
# add a field to it. Replaying the migration graph from scratch therefore
# always crashed with `KeyError: ('tenancy', 'domain')`, even though this
# migration itself was already marked applied and the real `tenant_domains`
# table has existed correctly in the live database the whole time.
#
# This CreateModel below is a state-only correction — verified against the
# actual live `tenant_domains` columns (id, domain, is_primary, tenant_id)
# and the current apps/tenancy/models.py::Domain + django_tenants
# DomainMixin field definitions. Since this migration is already recorded
# as applied, Django will not re-run it or emit any SQL for it — this only
# fixes how the migration graph reconstructs project state from here on.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0009_merge_20260520_1700"),
    ]

    operations = [
        migrations.CreateModel(
            name="Domain",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("domain", models.CharField(db_index=True, max_length=255, unique=True)),
                ("is_primary", models.BooleanField(db_index=True, default=False)),
                (
                    "tenant",
                    models.ForeignKey(
                        db_index=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="tenancy.schooltenant",
                    ),
                ),
            ],
            options={
                "db_table": "tenant_domains",
            },
        ),
    ]
