# Generated by Django 5.2.12 on 2026-05-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenancy", "0012_schooltenant_contact_address_affiliation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schooltenant",
            name="affiliation_number",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="schooltenant",
            name="campus_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="schooltenant",
            name="city",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="schooltenant",
            name="pin_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name="schooltenant",
            name="principal_email",
            field=models.EmailField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="schooltenant",
            name="principal_name",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="schooltenant",
            name="principal_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
