# Generated by Django 6.0.4 on 2026-05-29 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0015_invoice_partial_payments"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="superadmininvoicepayment",
            new_name="super_admin_invoice_26f535_idx",
            old_name="sa_inv_pay_inv_paid_idx",
        ),
    ]
