# Generated by Django 5.1.8 on 2026-07-24 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0018_schooltenant_school_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooltenant',
            name='school',
            field=models.OneToOneField(blank=True, help_text='The real ERP School row this tenant/billing record belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_record', to='tenancy.school'),
        ),
    ]
