# Generated by Django 5.1.8 on 2026-07-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0019_schooltenant_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooltenant',
            name='country',
            field=models.CharField(blank=True, default='India', max_length=64),
        ),
        migrations.AddField(
            model_name='schooltenant',
            name='medium_of_instruction',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='schooltenant',
            name='motto',
            field=models.CharField(blank=True, help_text='School motto/tagline, shown on receipts and the parent portal.', max_length=255),
        ),
        migrations.AddField(
            model_name='schooltenant',
            name='school_email',
            field=models.EmailField(blank=True, help_text="General/front-office email, distinct from the principal's inbox.", max_length=128),
        ),
        migrations.AddField(
            model_name='schooltenant',
            name='school_phone',
            field=models.CharField(blank=True, help_text="General/front-office phone, distinct from the principal's direct line.", max_length=20),
        ),
        migrations.AddField(
            model_name='schooltenant',
            name='website',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='schooltenant',
            name='year_established',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
