# Generated by Django 5.1.8 on 2026-07-31 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0020_schooltenant_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooltenant',
            name='geofence_radius_meters',
            field=models.PositiveIntegerField(blank=True, help_text='Radius (metres) around latitude/longitude for future staff clock-in/out geofencing.', null=True),
        ),
        migrations.AddField(
            model_name='schooltenant',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='schooltenant',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
