# Generated by Django 6.0.4 on 2026-08-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0021_schooltenant_geofence_radius_meters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='domain',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
