# Generated by Django 5.1.8 on 2026-05-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_add_must_change_password"),
    ]

    operations = [
        # Store email without a model-level unique=True so blank values are allowed.
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        # Partial unique index: only enforce uniqueness for non-empty emails.
        migrations.RunSQL(
            sql="CREATE UNIQUE INDEX IF NOT EXISTS users_email_nonempty_uniq ON users (email) WHERE email <> '';",
            reverse_sql="DROP INDEX IF EXISTS users_email_nonempty_uniq;",
        ),
    ]
