# Generated by Django 5.1.8 on 2026-05-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("tenancy", "0001_initial"),
        ("users", "0004_user_email_unique"),
    ]

    operations = [
        # The partial unique index was already created by RunSQL in 0004.
        # Use SeparateDatabaseAndState to register the constraint in Django's
        # migration state without executing any SQL against the DB.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddConstraint(
                    model_name="user",
                    constraint=models.UniqueConstraint(
                        condition=models.Q(("email__gt", "")),
                        fields=("email",),
                        name="users_email_nonempty_uniq",
                    ),
                ),
            ],
        ),
    ]
