# Generated by Django 6.0.4 on 2026-05-20 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_must_change_password"),
        ("users", "0005_user_users_email_nonempty_uniq"),
    ]

    operations = []
