# Generated by Django 6.0.3 on 2026-04-07 09:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_backfill_class_numeric_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="class",
            options={"ordering": ["numeric_order", "name", "id"]},
        ),
    ]
