# Generated by Django 5.1.8 on 2026-05-20 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_holiday_academic_year"),
        ("tenancy", "0003_remove_domain_tenant_delete_client_delete_domain"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streams",
                        to="tenancy.school",
                    ),
                ),
            ],
            options={
                "db_table": "academic_streams",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="class",
            name="streams",
            field=models.ManyToManyField(
                blank=True,
                help_text="Applicable to Senior Secondary (Grade 11-12).",
                related_name="classes",
                to="core.stream",
            ),
        ),
        migrations.AddConstraint(
            model_name="stream",
            constraint=models.UniqueConstraint(
                fields=("school", "name"), name="uq_stream_school_name"
            ),
        ),
    ]
