# Generated by Django 5.1.8 on 2026-06-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_manual_m2m_through_change"),
    ]

    operations = [
        migrations.AddField(
            model_name="academicyear",
            name="board",
            field=models.CharField(
                blank=True,
                help_text="Board/Curriculum e.g. CBSE, ICSE, State Board",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="academicyear",
            name="number_of_terms",
            field=models.CharField(
                blank=True,
                help_text="e.g. 2 Terms (Semester), 3 Terms (Trimester)",
                max_length=50,
                null=True,
            ),
        ),
    ]
