# Generated by Django 5.1.8 on 2026-06-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_academicyear_board_academicyear_number_of_terms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academicyear",
            name="board",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CBSE", "CBSE"),
                    ("ICSE", "ICSE"),
                    ("State Board", "State Board"),
                    ("IB", "IB (International Baccalaureate)"),
                    ("IGCSE", "IGCSE (Cambridge)"),
                    ("NIOS", "NIOS"),
                    ("Other", "Other"),
                ],
                help_text="Board/Curriculum",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="academicyear",
            name="number_of_terms",
            field=models.CharField(
                blank=True,
                choices=[
                    ("2 Terms (Semester)", "2 Terms (Semester)"),
                    ("3 Terms (Trimester)", "3 Terms (Trimester)"),
                    ("4 Terms (Quarter)", "4 Terms (Quarter)"),
                ],
                help_text="Number of terms per year",
                max_length=50,
                null=True,
            ),
        ),
    ]
