# Generated by Django 5.1.8 on 2026-07-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_academicyear_board_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='audience',
            field=models.CharField(choices=[('all', 'All (students & staff)'), ('staff_only', 'Staff only')], default='all', max_length=16),
        ),
    ]
