# Generated by Django 5.1.8 on 2026-07-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_holiday_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='is_optional',
            field=models.BooleanField(default=False),
        ),
    ]
