# Generated by Django 5.1.8 on 2026-07-29 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_holiday_is_optional'),
        ('tenancy', '0020_schooltenant_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='school',
            field=models.ForeignKey(blank=True, help_text='Null = applies to every school (e.g. a national holiday declared platform-wide).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='tenancy.school'),
        ),
    ]
