# Generated by Django 5.1.8 on 2026-08-18 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_holiday_school'),
        ('tenancy', '0021_schooltenant_geofence_radius_meters_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelScheduleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_group', models.CharField(choices=[('pre_primary', 'Pre-Primary'), ('primary', 'Primary'), ('middle', 'Middle'), ('secondary', 'Secondary'), ('senior_secondary', 'Senior Secondary')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('period_duration_minutes', models.PositiveSmallIntegerField()),
                ('periods_per_day', models.PositiveSmallIntegerField(help_text='Server-computed on save from start/end time, period duration, and break durations.')),
                ('snack_break_after_period', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('snack_break_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('lunch_break_after_period', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('lunch_break_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bus_dispersal_time', models.TimeField(blank=True, null=True)),
                ('pickup_time', models.TimeField(blank=True, null=True)),
                ('working_days', models.JSONField(blank=True, default=list, help_text="List of weekday codes, e.g. ['mon', 'tue', 'wed', 'thu', 'fri']")),
                ('is_configured', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_schedule_configs', to='core.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_schedule_configs', to='tenancy.school')),
            ],
            options={
                'db_table': 'level_schedule_configs',
                'ordering': ['level_group'],
                'constraints': [models.UniqueConstraint(fields=('school', 'academic_year', 'level_group'), name='uq_level_schedule_config_scope')],
            },
        ),
    ]
