# Generated by Django 5.1.8 on 2026-07-27 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0019_schooltenant_school'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallQueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, default='', max_length=64)),
                ('reason', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('emergency', 'Emergency')], default='normal', max_length=10)),
                ('source_link', models.CharField(blank=True, default='', max_length=255)),
                ('is_emergency', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_queue_entries', to='tenancy.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_queue_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'call_queue_entries',
                'ordering': ['done', '-is_emergency', '-created_at'],
                'indexes': [models.Index(fields=['school', 'user', 'done'], name='call_queue__school__4c4625_idx')],
            },
        ),
    ]
