# Generated by Django 5.1.8 on 2026-07-27 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0019_schooltenant_school'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('academic', 'Academic'), ('ops', 'Ops'), ('comms', 'Comms'), ('personal', 'Personal')], default='personal', max_length=10)),
                ('priority', models.CharField(default='normal', max_length=10)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('ai_generated', models.BooleanField(default=False)),
                ('ai_reason', models.TextField(blank=True, default='')),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='tenancy.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_todos',
                'ordering': ['completed', '-created_at'],
                'indexes': [models.Index(fields=['school', 'user', 'category'], name='user_todos_school__6ad897_idx'), models.Index(fields=['school', 'user', 'completed'], name='user_todos_school__a610cf_idx')],
            },
        ),
    ]
