# Generated by Django 5.1.8 on 2026-08-21 07:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_levelscheduleconfig"),
        ("exams", "0010_seatplansetting_seatplan_admitcardsetting_admitcard_and_more"),
        ("tenancy", "0021_schooltenant_geofence_radius_meters_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="examroutine",
            index=models.Index(fields=["exam_date"], name="idx_exam_routine_exam_date"),
        ),
    ]
