# Generated by Django 6.0.4 on 2026-09-08 11:10

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_levelscheduleconfig'),
        ('exams', '0011_performance_indexes'),
        ('students', '0026_student_aadhaar_no_student_abc_id_and_more'),
        ('tenancy', '0022_alter_domain_domain_alter_domain_is_primary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamGradeScaleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('style', models.CharField(choices=[('percentage', 'Percentage only'), ('letter', 'Letter grades'), ('gpa', 'GPA / points only')], default='letter', max_length=12)),
                ('min_pass_percent', models.DecimalField(decimal_places=2, default=Decimal('33.00'), max_digits=5)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'exam_grade_scale_groups',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExamResultModerationFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'exam_result_moderation_flags',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ReportCardSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible_to_class_teacher', models.BooleanField(default=True)),
                ('visible_to_subject_teacher', models.BooleanField(default=False)),
                ('template', models.CharField(choices=[('cbse', 'CBSE style'), ('icse', 'ICSE style'), ('cambridge', 'Cambridge style'), ('ib', 'IB style')], default='cbse', max_length=20)),
                ('include_photo', models.BooleanField(default=True)),
                ('include_co_scholastic', models.BooleanField(default=True)),
                ('include_attendance', models.BooleanField(default=True)),
                ('include_comments', models.BooleanField(default=True)),
                ('include_overall_notes', models.BooleanField(default=True)),
                ('include_improvement', models.BooleanField(default=True)),
                ('moderation_workflow', models.CharField(choices=[('as_you_go', 'As-you-go'), ('bulk', 'Bulk'), ('custom', 'Custom')], default='as_you_go', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'exam_report_card_settings',
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='examgradescale',
            name='uq_exam_grade_scale_school_name',
        ),
        migrations.AddField(
            model_name='examresultpublish',
            name='principal_signoff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examresultpublish',
            name='principal_signoff_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examresultpublish',
            name='principal_signoff_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_result_publish_signoffs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examtype',
            name='counts_to_average',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='examtype',
            name='weight_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='examgradescalegroup',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_grade_scale_groups', to='tenancy.school'),
        ),
        migrations.AddField(
            model_name='examgradescale',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bands', to='exams.examgradescalegroup'),
        ),
        migrations.AddConstraint(
            model_name='examgradescale',
            constraint=models.UniqueConstraint(fields=('school', 'group', 'name'), name='uq_exam_grade_scale_school_group_name'),
        ),
        migrations.AddField(
            model_name='examresultmoderationflag',
            name='exam_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_flags', to='exams.examtype'),
        ),
        migrations.AddField(
            model_name='examresultmoderationflag',
            name='mark_register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_flags', to='exams.exammarkregister'),
        ),
        migrations.AddField(
            model_name='examresultmoderationflag',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_result_moderation_flags_resolved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examresultmoderationflag',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_result_moderation_flags', to='tenancy.school'),
        ),
        migrations.AddField(
            model_name='examresultmoderationflag',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_result_moderation_flags', to='core.class'),
        ),
        migrations.AddField(
            model_name='examresultmoderationflag',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_result_moderation_flags', to='core.section'),
        ),
        migrations.AddField(
            model_name='examresultmoderationflag',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_result_moderation_flags', to='students.student'),
        ),
        migrations.AddField(
            model_name='reportcardsetting',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_card_settings', to='core.academicyear'),
        ),
        migrations.AddField(
            model_name='reportcardsetting',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_card_settings', to='tenancy.school'),
        ),
        migrations.AddConstraint(
            model_name='examgradescalegroup',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='uq_exam_grade_scale_group_school_name'),
        ),
        migrations.AddConstraint(
            model_name='reportcardsetting',
            constraint=models.UniqueConstraint(fields=('school', 'academic_year'), name='uq_report_card_setting_scope'),
        ),
    ]
