# Generated by Django 6.0.4 on 2026-09-18 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_levelscheduleconfig'),
        ('exams', '0012_examgradescalegroup_examresultmoderationflag_and_more'),
        ('students', '0026_student_aadhaar_no_student_abc_id_and_more'),
        ('tenancy', '0022_alter_domain_domain_alter_domain_is_primary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exammarkregister',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Set True when teacher submits. Admin can unlock.'),
        ),
        migrations.AddField(
            model_name='exammarkregister',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exammarkregister',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_mark_registers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('marks_open', 'Marks Open'), ('closed', 'Closed')], default='draft', max_length=12),
        ),
        migrations.CreateModel(
            name='ExamAdmitCardFeeOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Mandatory reason provided by the Principal.')),
                ('outstanding_balance', models.DecimalField(decimal_places=2, help_text='Outstanding balance at the time of override.', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admit_card_fee_overrides', to='exams.examtype')),
                ('overridden_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admit_card_fee_overrides', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admit_card_fee_overrides', to='tenancy.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admit_card_fee_overrides', to='students.student')),
            ],
            options={
                'db_table': 'exam_admit_card_fee_overrides',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamFeeGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, help_text='When True, admit card generation is blocked for students with outstanding dues.')),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_fee_gates', to='core.academicyear')),
                ('enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_fee_gates_enabled', to=settings.AUTH_USER_MODEL)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam_fee_gate', to='tenancy.school')),
            ],
            options={
                'db_table': 'exam_fee_gates',
            },
        ),
    ]
