# Generated by Django 5.1.8 on 2026-07-27 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0019_schooltenant_school'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(db_index=True, max_length=255)),
                ('color', models.CharField(choices=[('yellow', 'Yellow'), ('pink', 'Pink'), ('green', 'Green'), ('blue', 'Blue'), ('purple', 'Purple')], default='yellow', max_length=10)),
                ('text', models.TextField(blank=True, default='')),
                ('position_x', models.IntegerField(default=80)),
                ('position_y', models.IntegerField(default=120)),
                ('pinned', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='tenancy.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notes',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['school', 'user', 'route'], name='notes_school__bb5963_idx'), models.Index(fields=['school', 'user', 'pinned'], name='notes_school__9bbb0f_idx')],
            },
        ),
    ]
