# Generated by Django 5.1.8 on 2026-07-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='height',
            field=models.IntegerField(default=160),
        ),
        migrations.AddField(
            model_name='note',
            name='width',
            field=models.IntegerField(default=240),
        ),
    ]
