# Generated by GitHub Copilot

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("academics", "0004_lesson_lessonplanner_lessontopic_lessontopicdetail_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroutineslot",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routine_slots",
                to="core.subject",
            ),
        ),
    ]
