# Generated by Django 5.1.8 on 2026-07-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_staff_assignment_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsubjectentry',
            name='subject_type',
            field=models.CharField(choices=[('core', 'Mandatory'), ('first_language', 'First Language'), ('second_language', 'Second Language'), ('third_language', 'Third Language'), ('sport', 'Sports'), ('club', 'Clubs'), ('co_curricular', 'Co-curricular'), ('optional', 'Optional Subjects')], default='core', max_length=20),
        ),
    ]
