# Generated by Django 5.1.8 on 2026-08-18 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_alter_classsubjectentry_subject_type'),
        ('core', '0027_alter_holiday_school'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classroutineslot',
            name='class_room',
            field=models.ForeignKey(blank=True, help_text='Real FK replacement for the legacy `room_id` loose reference.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routine_slots_room', to='core.classroom'),
        ),
        migrations.AddField(
            model_name='classroutineslot',
            name='period',
            field=models.ForeignKey(blank=True, help_text='Real FK replacement for the legacy `class_period_id` loose reference.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routine_slots_period', to='core.classperiod'),
        ),
        migrations.AddField(
            model_name='lessonplanner',
            name='class_room',
            field=models.ForeignKey(blank=True, help_text='Real FK replacement for the legacy `room_id` loose reference.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_planners_room', to='core.classroom'),
        ),
        migrations.AddField(
            model_name='lessonplanner',
            name='period',
            field=models.ForeignKey(blank=True, help_text='Real FK replacement for the legacy `class_period_id` loose reference.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_planners_period', to='core.classperiod'),
        ),
        migrations.AddField(
            model_name='lessonplanner',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lessonplanner',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonplanner',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_plans_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonplanner',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonplanner',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_plans_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonplanner',
            name='workflow_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('revision_requested', 'Revision Requested')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='classroutineslot',
            name='class_period_id',
            field=models.PositiveIntegerField(blank=True, help_text='Deprecated loose reference — use `period` instead.', null=True),
        ),
        migrations.AlterField(
            model_name='classroutineslot',
            name='day_id',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Deprecated legacy numeric day — use `day` instead.', null=True),
        ),
        migrations.AlterField(
            model_name='classroutineslot',
            name='room_id',
            field=models.PositiveIntegerField(blank=True, help_text='Deprecated loose reference — use `class_room` instead.', null=True),
        ),
        migrations.AlterField(
            model_name='lessonplanner',
            name='class_period_id',
            field=models.PositiveIntegerField(blank=True, help_text='Deprecated loose reference — use `period` instead.', null=True),
        ),
        migrations.AlterField(
            model_name='lessonplanner',
            name='completed_status',
            field=models.CharField(blank=True, choices=[('Planned', 'Planned'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], help_text='Delivery progress of the lesson itself (not the review workflow below).', max_length=50),
        ),
        migrations.AlterField(
            model_name='lessonplanner',
            name='room_id',
            field=models.PositiveIntegerField(blank=True, help_text='Deprecated loose reference — use `class_room` instead.', null=True),
        ),
        migrations.CreateModel(
            name='LessonPlanApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('revision_requested', 'Revision Requested')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_plan_approval_actions', to=settings.AUTH_USER_MODEL)),
                ('lesson_planner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_log', to='academics.lessonplanner')),
            ],
            options={
                'db_table': 'lesson_plan_approval_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
