# Generated by Django 5.1.8 on 2026-08-21 07:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "academics",
            "0010_classroutineslot_class_room_classroutineslot_period_and_more",
        ),
        ("core", "0028_levelscheduleconfig"),
        ("tenancy", "0021_schooltenant_geofence_radius_meters_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="classroutineslot",
            index=models.Index(fields=["active_status"], name="idx_crs_active_status"),
        ),
        migrations.AddIndex(
            model_name="classsubjectassignment",
            index=models.Index(fields=["active_status"], name="idx_csa_active_status"),
        ),
        migrations.AddIndex(
            model_name="classsubjectentry",
            index=models.Index(fields=["active_status"], name="idx_cse_active_status"),
        ),
        migrations.AddIndex(
            model_name="classteacherassignment",
            index=models.Index(fields=["active_status"], name="idx_cta_active_status"),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["active_status"], name="idx_lesson_active_status"
            ),
        ),
    ]
