# Generated by Django 6.0.4 on 2026-05-08 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0020_merge_20260504_1756"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIRequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt_hash", models.CharField(db_index=True, max_length=64)),
                ("prompt", models.TextField()),
                ("response", models.TextField(blank=True)),
                (
                    "cost_estimate",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                ("cache_hit", models.BooleanField(default=False)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_request_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "competitions_ai_request_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competition_clubs",
                        to="tenancy.school",
                    ),
                ),
            ],
            options={
                "db_table": "competitions_club",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("date", models.DateField()),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("intra_class", "Intra-Class"),
                            ("inter_class", "Inter-Class"),
                            ("intra_school", "Intra-School"),
                            ("inter_school", "Inter-School"),
                            ("district", "District"),
                            ("state", "State"),
                            ("national", "National"),
                            ("international", "International"),
                        ],
                        default="intra_school",
                        max_length=30,
                    ),
                ),
                (
                    "comp_type",
                    models.CharField(
                        choices=[
                            ("academic", "Academic"),
                            ("sports", "Sports"),
                            ("cultural", "Cultural"),
                            ("arts", "Arts"),
                            ("debate", "Debate"),
                            ("stem", "STEM"),
                            ("other", "Other"),
                        ],
                        default="academic",
                        max_length=30,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=200)),
                ("opponent", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="competitions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competitions",
                        to="tenancy.school",
                    ),
                ),
            ],
            options={
                "db_table": "competitions_competition",
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="House",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("color", models.CharField(blank=True, max_length=20)),
                ("motto", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competition_houses",
                        to="tenancy.school",
                    ),
                ),
            ],
            options={
                "db_table": "competitions_house",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="competitions.competition",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="competition_teams",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "competitions_team",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("1st", "1st Place"),
                            ("2nd", "2nd Place"),
                            ("3rd", "3rd Place"),
                            ("consolation", "Consolation"),
                            ("participation", "Participation"),
                            ("not_participated", "Not Participated"),
                        ],
                        max_length=20,
                    ),
                ),
                ("points", models.IntegerField(default=0)),
                ("personal_contribution", models.TextField(blank=True)),
                ("performance_notes", models.TextField(blank=True)),
                ("ai_generated", models.BooleanField(default=False)),
                (
                    "ai_prompt_hash",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("ai_response", models.TextField(blank=True)),
                ("ai_timestamp", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="results",
                        to="competitions.club",
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="competitions.competition",
                    ),
                ),
                (
                    "house",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="results",
                        to="competitions.house",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competition_results",
                        to="students.student",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="results",
                        to="competitions.team",
                    ),
                ),
            ],
            options={
                "db_table": "competitions_result",
                "ordering": ["competition_id", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="club",
            constraint=models.UniqueConstraint(
                fields=("school", "name"), name="uq_club_school_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="house",
            constraint=models.UniqueConstraint(
                fields=("school", "name"), name="uq_house_school_name"
            ),
        ),
        migrations.AddIndex(
            model_name="result",
            index=models.Index(
                fields=["competition", "position"],
                name="competition_competi_452579_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="result",
            index=models.Index(
                fields=["student"], name="competition_student_056810_idx"
            ),
        ),
    ]
