'use client';

import React, { useState } from 'react';
import { competitionsApi } from '@/lib/competitionsApi';

/**
 * CompetitionForm
 *  • Premium expanded card while editing.
 *  • Collapses into a sleek "context chip" header once saved, freeing screen space.
 *  • Type selector uses visual icon-chips instead of a select box.
 *  • Falls back to a local stub if backend isn't wired so the UI never blocks the user.
 */

const LEVELS = [
  ['intra_class', 'Intra-Class'], ['inter_class', 'Inter-Class'],
  ['intra_school', 'Intra-School'], ['inter_house', 'Inter-House'],
  ['inter_school', 'Inter-School'],
  ['district', 'District'], ['state', 'State'],
  ['national', 'National'], ['international', 'International'],
];
const TYPES = [
  ['academic', 'Academic', '📚'], ['sports', 'Sports', '🏆'],
  ['cultural', 'Cultural', '🎭'], ['arts', 'Arts', '🎨'],
  ['debate', 'Debate', '🎤'], ['stem', 'STEM', '🔬'],
  ['other', 'Other', '✨'],
];

// Sports catalogue — drives team-mode role presets and AI tone.
// Ordered roughly by popularity in Indian school setting.
const SPORTS = [
  { v: 'cricket',     label: 'Cricket',     icon: '🏏' },
  { v: 'football',    label: 'Football',    icon: '⚽' },
  { v: 'basketball',  label: 'Basketball',  icon: '🏀' },
  { v: 'hockey',      label: 'Hockey',      icon: '🏑' },
  { v: 'volleyball',  label: 'Volleyball',  icon: '🏐' },
  { v: 'badminton',   label: 'Badminton',   icon: '🏸' },
  { v: 'tennis',      label: 'Tennis',      icon: '🎾' },
  { v: 'tabletennis', label: 'Table Tennis',icon: '🏓' },
  { v: 'kabaddi',     label: 'Kabaddi',     icon: '🤼' },
  { v: 'kho-kho',     label: 'Kho-Kho',     icon: '🏃' },
  { v: 'athletics',   label: 'Athletics',   icon: '🏃‍♂️' },
  { v: 'relay',       label: 'Relay',       icon: '🥎' },
  { v: 'swimming',    label: 'Swimming',    icon: '🏊' },
  { v: 'chess',       label: 'Chess',       icon: '♟️' },
  { v: 'carrom',      label: 'Carrom',      icon: '🎯' },
  { v: 'yoga',        label: 'Yoga',        icon: '🧘' },
  { v: 'gymnastics',  label: 'Gymnastics',  icon: '🤸' },
  { v: 'taekwondo',   label: 'Taekwondo',   icon: '🥋' },
  { v: 'other',       label: 'Other',       icon: '🏅' },
];

// Default 4 houses — schools usually customise these but the colour set is universal.
// Override by passing `houses` prop or wire to backend `/houses/` later.
const DEFAULT_HOUSES = [
  { id: 'red',    name: 'Red',    icon: '🔥', tone: 'bg-rose-100 text-rose-900 border-rose-300 ring-rose-300/60',     dot: 'bg-rose-500' },
  { id: 'blue',   name: 'Blue',   icon: '💧', tone: 'bg-sky-100 text-sky-900 border-sky-300 ring-sky-300/60',         dot: 'bg-sky-500' },
  { id: 'green',  name: 'Green',  icon: '🌿', tone: 'bg-emerald-100 text-emerald-900 border-emerald-300 ring-emerald-300/60', dot: 'bg-emerald-500' },
  { id: 'yellow', name: 'Yellow', icon: '⚡', tone: 'bg-amber-100 text-amber-900 border-amber-300 ring-amber-300/60', dot: 'bg-amber-500' },
];

// One-click presets — each fills type, level, and (where useful) location.
// Name + AI notes are then auto-generated by the smart suggesters.
const QUICK_PRESETS = [
  { label: 'Inter-House Quiz',   icon: '🏠📚', values: { comp_type: 'academic', level: 'inter_house', location: 'Auditorium' } },
  { label: 'Inter-House Sports', icon: '🏠🏆', values: { comp_type: 'sports',   level: 'inter_house', location: 'School Ground' } },
  { label: 'Annual Cultural',    icon: '🎭',   values: { comp_type: 'cultural', level: 'intra_school', location: 'Auditorium' } },
  { label: 'Inter-School Debate',icon: '🎤',   values: { comp_type: 'debate',   level: 'inter_school' } },
  { label: 'Science Fair',       icon: '🔬',   values: { comp_type: 'stem',     level: 'intra_school', location: 'Science Lab' } },
  { label: 'Art Showcase',       icon: '🎨',   values: { comp_type: 'arts',     level: 'intra_school', location: 'Art Room' } },
];

/** Smart on-device "AI" assist — instant, no API call, no waiting. */
function suggestName(form, houseA, houseB) {
  const typeMap = { academic: 'Quiz', sports: 'Tournament', cultural: 'Festival', arts: 'Showcase', debate: 'Debate', stem: 'Challenge', other: 'Competition' };
  const t = typeMap[form.comp_type] || 'Competition';
  if (form.level === 'inter_house' && houseA && houseB) {
    return `Inter-House ${t} Final · ${houseA.name} vs ${houseB.name}`;
  }
  const lvl = (LEVELS.find((l) => l[0] === form.level)?.[1]) || '';
  return `${lvl} ${t} ${new Date(form.date || Date.now()).getFullYear()}`.trim();
}

function suggestNotes(form, houseA, houseB) {  const typeBlurb = {
    academic: 'Tests subject mastery, quick recall, and clear reasoning under timed pressure.',
    sports:   'Emphasises teamwork, stamina, sportsmanship, and tactical awareness.',
    cultural: 'Celebrates expression, stagecraft, originality, and cultural awareness.',
    arts:     'Rewards creativity, technique, composition, and emotional storytelling.',
    debate:   'Judged on argument structure, evidence, rebuttal, and persuasive delivery.',
    stem:     'Assesses problem-solving, scientific method, innovation, and presentation.',
    other:    'Recognises preparation, effort, and graceful conduct throughout the event.',
  }[form.comp_type] || '';
  const lvl = (LEVELS.find((l) => l[0] === form.level)?.[1]) || '';
  const parts = [
    `Event: ${form.name || '(untitled)'} · ${lvl}${form.location ? ' at ' + form.location : ''}.`,
    typeBlurb,
  ];
  if (form.level === 'inter_house' && houseA && houseB) {
    parts.push(`Finalist houses: ${houseA.name} vs ${houseB.name}. Encourage healthy rivalry, team spirit, and respect for opponents.`);
  } else if (form.opponent) {
    parts.push(`Hosted with/against: ${form.opponent}.`);
  }
  parts.push('Tone for reviews: warm, age-appropriate, confidence-building. Highlight effort over outcome and offer one concrete next step.');
  return parts.join(' ');
}

const inputCls =
  'mt-1.5 block w-full rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-[13px] ' +
  'text-slate-900 placeholder-slate-400 shadow-[0_1px_2px_rgba(15,23,42,0.04)] ' +
  'focus:outline-none focus:ring-2 focus:ring-purple-400/60 focus:border-purple-400 transition';

export default function CompetitionForm({ schoolId, value, onSaved, houses, students = [] }) {
  const HOUSES = (houses && houses.length >= 2) ? houses : DEFAULT_HOUSES;
  const [form, setForm] = useState(
    value || {
      name: '', date: new Date().toISOString().slice(0, 10),
      level: 'intra_school', comp_type: 'academic',
      sport_type: '',
      location: '', opponent: '', notes: '',
      house_a: null, house_b: null,
      classes: [],          // for inter_class
      class_name: '',       // for intra_class
      sections: [],         // for intra_class (optional narrowing)
    }
  );
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');

  const set = (k) => (e) => setForm((f) => ({ ...f, [k]: e.target.value }));
  const houseA = form.house_a ? HOUSES.find((h) => h.id === form.house_a) : null;
  const houseB = form.house_b ? HOUSES.find((h) => h.id === form.house_b) : null;
  const isInterHouse  = form.level === 'inter_house';
  const isInterClass  = form.level === 'inter_class';
  const isIntraClass  = form.level === 'intra_class';

  // Distinct classes & sections derived live from the school roster
  const ALL_CLASSES = React.useMemo(
    () => Array.from(new Set(students.map((s) => s.class_name).filter(Boolean)))
              .sort((a, b) => String(a).localeCompare(String(b), undefined, { numeric: true })),
    [students],
  );
  const SECTIONS_FOR_CLASS = React.useMemo(() => {
    if (!form.class_name) return [];
    return Array.from(new Set(
      students.filter((s) => s.class_name === form.class_name).map((s) => s.section).filter((x) => x && x !== '-')
    )).sort();
  }, [students, form.class_name]);

  function toggleInArr(key, val) {
    setForm((f) => {
      const arr = Array.isArray(f[key]) ? f[key] : [];
      return { ...f, [key]: arr.includes(val) ? arr.filter((x) => x !== val) : [...arr, val] };
    });
  }
  function pickClassSingle(name) {
    setForm((f) => ({ ...f, class_name: f.class_name === name ? '' : name, sections: [] }));
  }

  function pickHouse(slot, id) {
    setForm((f) => {
      // If user re-clicks the chosen one, clear it. If picking same id in other slot, swap.
      if (slot === 'a') {
        if (f.house_a === id) return { ...f, house_a: null };
        if (f.house_b === id) return { ...f, house_a: id, house_b: f.house_a };
        return { ...f, house_a: id };
      }
      if (f.house_b === id) return { ...f, house_b: null };
      if (f.house_a === id) return { ...f, house_b: id, house_a: f.house_b };
      return { ...f, house_b: id };
    });
  }

  function magicFillName() {
    setForm((f) => ({ ...f, name: suggestName(f, houseA, houseB) }));
  }
  function magicFillNotes() {
    setForm((f) => ({ ...f, notes: suggestNotes(f, houseA, houseB) }));
  }

  async function submit(e) {
    e.preventDefault();
    const cleaned = titleCaseLocal(form.name);
    if (!cleaned.trim()) { setError('Please give the competition a name.'); return; }
    setSaving(true); setError('');
    const payload = { ...form, name: cleaned };
    try {
      const created = await competitionsApi.createCompetition({ ...payload, school: schoolId });
      onSaved?.(created);
    } catch (err) {
      // Graceful fallback — let the user keep working even if the backend route isn't wired yet.
      onSaved?.({ ...payload, id: Date.now(), _local: true });
      console.warn('[InspireHub] API create failed, using local stub:', err?.message);
    } finally { setSaving(false); }
  }
  function titleCaseLocal(s) {
    if (!s || typeof s !== 'string') return s || '';
    const small = new Set(['a','an','and','as','at','but','by','for','in','of','on','or','the','to','vs','via']);
    return s.trim().split(/\s+/).map((w, i) => {
      if (/^[A-Z]{2,}$/.test(w)) return w;
      if (i > 0 && small.has(w.toLowerCase())) return w.toLowerCase();
      return w.charAt(0).toUpperCase() + w.slice(1).toLowerCase();
    }).join(' ');
  }

  // === Collapsed "context chip" mode ===
  if (value?.id) {
    const typeIcon = TYPES.find((t) => t[0] === value.comp_type)?.[2] || '✨';
    const levelLabel = LEVELS.find((l) => l[0] === value.level)?.[1] || value.level;
    return (
      <div className="group relative overflow-hidden rounded-2xl border border-slate-200/80 bg-white shadow-[0_2px_8px_-2px_rgba(15,23,42,0.06)]">
        <div className="absolute inset-0 bg-gradient-to-r from-purple-50/60 via-transparent to-pink-50/40 pointer-events-none" />
        <div className="relative flex items-center gap-4 p-4 md:p-5">
          <span className="inline-flex h-12 w-12 items-center justify-center rounded-2xl bg-gradient-to-br from-slate-100 to-white border border-slate-200 text-[22px] shadow-inner">
            {typeIcon}
          </span>
          <div className="min-w-0 flex-1">
            <div className="flex items-center gap-2 flex-wrap">
              <h3 className="text-[15px] font-extrabold text-slate-900 tracking-tight truncate">{value.name}</h3>
              {value._local && (
                <span className="inline-flex items-center gap-1 rounded-md bg-amber-50 border border-amber-200 text-amber-700 text-[10px] font-bold px-1.5 py-0.5">
                  <span className="h-1.5 w-1.5 rounded-full bg-amber-500" /> offline draft
                </span>
              )}
            </div>
            <div className="mt-1 flex items-center gap-1.5 flex-wrap text-[11px]">
              <Pill icon="📅" text={value.date} />
              <Pill icon="🎯" text={levelLabel} />
              {value.location && <Pill icon="📍" text={value.location} />}
              {value.opponent && <Pill icon="⚔️" text={value.opponent} />}
              {value.house_a && (() => {
                const hA = HOUSES.find((h) => h.id === value.house_a);
                const hB = HOUSES.find((h) => h.id === value.house_b);
                if (!hA) return null;
                return (
                  <span className="inline-flex items-center gap-1 rounded-md bg-white border border-slate-200 px-2 py-0.5 font-bold text-slate-700">
                    <span className={'inline-block h-2 w-2 rounded-full ' + hA.dot} />{hA.name}
                    {hB && <><span className="text-slate-400 mx-1">vs</span><span className={'inline-block h-2 w-2 rounded-full ' + hB.dot} />{hB.name}</>}
                  </span>
                );
              })()}
            </div>
          </div>
          <button
            onClick={() => onSaved?.(null)}
            className="inline-flex items-center gap-1 text-[12px] font-bold text-purple-700 hover:text-purple-900 px-3 py-1.5 rounded-lg hover:bg-purple-100/70 transition"
          >
            <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2.2}><path d="M11 4H4v16h16v-7M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z" /></svg>
            Edit
          </button>
        </div>
      </div>
    );
  }

  // === Expanded edit mode ===
  return (
    <form
      onSubmit={submit}
      className="relative overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-[0_4px_24px_-8px_rgba(15,23,42,0.08)]"
    >
      <div className="absolute top-0 left-0 right-0 h-1 bg-gradient-to-r from-[#7C3AED] via-fuchsia-500 to-[#EC4899]" />
      <div className="p-5 md:p-6 grid grid-cols-1 md:grid-cols-12 gap-4">
        <div className="md:col-span-12 flex items-center gap-2 mb-1">
          <span className="inline-flex h-6 w-6 items-center justify-center rounded-md bg-purple-100 text-purple-700 text-[11px] font-extrabold">1</span>
          <h3 className="text-[13.5px] font-extrabold text-slate-900">Competition details</h3>
          <span className="text-[11px] text-slate-400 font-medium">Saved automatically as you continue</span>
        </div>

        {/* === Quick-start presets — one click fills the whole form === */}
        <div className="md:col-span-12 -mt-1">
          <div className="flex items-center gap-2 flex-wrap">
            <span className="text-[10.5px] font-extrabold uppercase tracking-[0.08em] text-slate-500">⚡ Quick start</span>
            {QUICK_PRESETS.map((p) => (
              <button key={p.label} type="button"
                onClick={() => {
                  setForm((f) => {
                    const merged = { ...f, ...p.values };
                    return { ...merged, name: suggestName(merged, HOUSES.find(h=>h.id===merged.house_a), HOUSES.find(h=>h.id===merged.house_b)),
                                        notes: suggestNotes(merged, HOUSES.find(h=>h.id===merged.house_a), HOUSES.find(h=>h.id===merged.house_b)) };
                  });
                }}
                className="group inline-flex items-center gap-1.5 rounded-full border border-slate-200 bg-white hover:border-purple-300 hover:bg-purple-50/60 px-2.5 py-1 text-[11px] font-bold text-slate-700 hover:text-purple-800 transition">
                <span aria-hidden>{p.icon}</span>{p.label}
              </button>
            ))}
            <span className="text-[10.5px] text-slate-400 italic">tap one — name, type, level &amp; AI notes auto-fill</span>
          </div>
        </div>

        <label className="md:col-span-12">
          <span className="flex items-center gap-2 text-[10.5px] font-extrabold uppercase tracking-[0.08em] text-slate-500">
            Name *
            <button type="button" onClick={magicFillName}
              className="ml-auto inline-flex items-center gap-1 rounded-md bg-gradient-to-r from-purple-100 to-pink-100 text-purple-800 hover:from-purple-200 hover:to-pink-200 border border-purple-200 px-2 py-0.5 text-[10px] font-bold normal-case tracking-normal transition"
              title="Suggest a smart name based on type, level and finalists">
              ✨ Suggest
            </button>
          </span>
          <input className={inputCls} value={form.name} onChange={set('name')} placeholder="e.g. Inter-House Quiz Championship" required autoFocus />
        </label>

        <label className="md:col-span-3">
          <span className="text-[10.5px] font-extrabold uppercase tracking-[0.08em] text-slate-500">Date</span>
          <input type="date" className={inputCls} value={form.date} onChange={set('date')} />
        </label>

        <div className="md:col-span-9">
          <span className="text-[10.5px] font-extrabold uppercase tracking-[0.08em] text-slate-500">Type</span>
          <div className="mt-1.5 flex flex-wrap gap-1.5">
            {TYPES.map(([v, label, icon]) => {
              const active = form.comp_type === v;
              return (
                <button
                  key={v} type="button"
                  onClick={() => setForm((f) => ({ ...f, comp_type: v, sport_type: v === 'sports' ? f.sport_type : '' }))}
                  className={
                    'inline-flex items-center gap-1.5 rounded-xl px-3 py-2 text-[12px] font-bold border transition-all duration-150 ' +
                    (active
                      ? 'bg-gradient-to-br from-[#7C3AED] to-[#EC4899] text-white border-transparent shadow-[0_6px_16px_-6px_rgba(124,58,237,0.6)] scale-[1.03]'
                      : 'bg-white text-slate-700 border-slate-200 hover:border-purple-300 hover:bg-purple-50/60 hover:-translate-y-[1px]')
                  }
                >
                  <span aria-hidden>{icon}</span>{label}
                </button>
              );
            })}
          </div>

          {/* === Sport picker — appears only when Sports is selected === */}
          {form.comp_type === 'sports' && (
            <div className="mt-3 rounded-xl border border-amber-200 bg-gradient-to-br from-amber-50/70 via-white to-orange-50/50 p-3 animate-[fadeIn_0.18s_ease-out]">
              <div className="flex items-center gap-2 mb-2">
                <span aria-hidden className="text-[14px]">🏟️</span>
                <span className="text-[10.5px] font-extrabold uppercase tracking-[0.08em] text-amber-900">Which sport?</span>
                <span className="text-[10.5px] text-amber-800/80">drives captain / vice-captain roles when marking results</span>
                {form.sport_type && (
                  <button type="button" onClick={() => setForm((f) => ({ ...f, sport_type: '' }))}
                    className="ml-auto text-[10.5px] font-bold text-amber-700 hover:text-amber-900 underline-offset-2 hover:underline">Clear</button>
                )}
              </div>
              <div className="flex flex-wrap gap-1.5">
                {SPORTS.map((sp) => {
                  const on = form.sport_type === sp.v;
                  return (
                    <button
                      key={sp.v} type="button"
                      onClick={() => setForm((f) => ({ ...f, sport_type: sp.v }))}
                      className={
                        'inline-flex items-center gap-1.5 rounded-lg border px-2.5 py-1.5 text-[11.5px] font-bold transition-all duration-150 ' +
                        (on
                          ? 'bg-amber-500 text-white border-amber-500 shadow-[0_4px_12px_-4px_rgba(245,158,11,0.6)] scale-[1.04]'
                          : 'bg-white text-slate-700 border-slate-200 hover:border-amber-400 hover:bg-amber-50/70 hover:-translate-y-[1px]')
                      }
                    >
                      <span aria-hidden>{sp.icon}</span>{sp.label}
                    </button>
                  );
                })}
              </div>
            </div>
          )}
        </div>

        <label className="md:col-span-4">
          <span className="text-[10.5px] font-extrabold uppercase tracking-[0.08em] text-slate-500">Level</span>
          <select className={inputCls} value={form.level} onChange={set('level')}>
            {LEVELS.map(([v, l]) => <option key={v} value={v}>{l}</option>)}
          </select>
        </label>
        <label className="md:col-span-4">
          <span className="text-[10.5px] font-extrabold uppercase tracking-[0.08em] text-slate-500">Location</span>
          <input className={inputCls} value={form.location} onChange={set('location')} placeholder="School auditorium" />
        </label>
        <label className={'md:col-span-4 ' + ((isInterHouse || isInterClass || isIntraClass) ? 'opacity-50 pointer-events-none' : '')}>
          <span className="text-[10.5px] font-extrabold uppercase tracking-[0.08em] text-slate-500">Opponent / Host</span>
          <input className={inputCls} value={form.opponent} onChange={set('opponent')} placeholder={(isInterHouse || isInterClass || isIntraClass) ? 'Set scope below' : 'Optional'} disabled={isInterHouse || isInterClass || isIntraClass} />
        </label>

        {/* === Inter-Class scope picker === */}
        {isInterClass && (
          <div className="md:col-span-12 relative overflow-hidden rounded-2xl border border-sky-200 bg-gradient-to-br from-sky-50/60 to-indigo-50/60 p-4">
            <div className="flex items-center gap-2 mb-2">
              <span className="text-[15px]">🎓</span>
              <span className="text-[12.5px] font-extrabold text-slate-900">Pick the participating classes</span>
              <span className="text-[10.5px] text-slate-500">select 2 or more · only students from these classes will appear in the picker</span>
              {form.classes?.length > 0 && (
                <button type="button" onClick={() => setForm((f) => ({ ...f, classes: [] }))}
                        className="ml-auto text-[10.5px] font-bold text-slate-500 hover:text-slate-800">Clear</button>
              )}
            </div>
            {ALL_CLASSES.length === 0 ? (
              <div className="text-[12px] text-slate-500 italic">No class roster available — open from a Student Group page.</div>
            ) : (
              <div className="flex flex-wrap gap-1.5">
                {ALL_CLASSES.map((c) => {
                  const on = form.classes?.includes(c);
                  return (
                    <button key={c} type="button" onClick={() => toggleInArr('classes', c)}
                      className={'rounded-lg border-2 px-3 py-1.5 text-[12px] font-bold transition-all ' +
                        (on ? 'bg-sky-600 text-white border-sky-600 shadow-sm scale-[1.02]'
                            : 'bg-white text-slate-700 border-slate-200 hover:border-sky-400')}>
                      {c}
                    </button>
                  );
                })}
              </div>
            )}
          </div>
        )}

        {/* === Intra-Class scope picker (single class + optional sections) === */}
        {isIntraClass && (
          <div className="md:col-span-12 relative overflow-hidden rounded-2xl border border-emerald-200 bg-gradient-to-br from-emerald-50/60 to-teal-50/60 p-4 space-y-3">
            <div className="flex items-center gap-2">
              <span className="text-[15px]">🏫</span>
              <span className="text-[12.5px] font-extrabold text-slate-900">Pick the class</span>
              <span className="text-[10.5px] text-slate-500">single class · students will be limited to this class</span>
            </div>
            {ALL_CLASSES.length === 0 ? (
              <div className="text-[12px] text-slate-500 italic">No class roster available — open from a Student Group page.</div>
            ) : (
              <div className="flex flex-wrap gap-1.5">
                {ALL_CLASSES.map((c) => {
                  const on = form.class_name === c;
                  return (
                    <button key={c} type="button" onClick={() => pickClassSingle(c)}
                      className={'rounded-lg border-2 px-3 py-1.5 text-[12px] font-bold transition-all ' +
                        (on ? 'bg-emerald-600 text-white border-emerald-600 shadow-sm scale-[1.02]'
                            : 'bg-white text-slate-700 border-slate-200 hover:border-emerald-400')}>
                      {c}
                    </button>
                  );
                })}
              </div>
            )}
            {form.class_name && SECTIONS_FOR_CLASS.length > 1 && (
              <div className="pt-2 border-t border-emerald-200/60">
                <div className="flex items-center gap-2 mb-1.5">
                  <span className="text-[11px] font-extrabold uppercase tracking-[0.08em] text-emerald-800">Narrow to sections</span>
                  <span className="text-[10.5px] text-slate-500">optional · leave empty for all sections of {form.class_name}</span>
                </div>
                <div className="flex flex-wrap gap-1.5">
                  {SECTIONS_FOR_CLASS.map((s) => {
                    const on = form.sections?.includes(s);
                    return (
                      <button key={s} type="button" onClick={() => toggleInArr('sections', s)}
                        className={'rounded-md border px-2.5 py-1 text-[11.5px] font-bold transition ' +
                          (on ? 'bg-teal-600 text-white border-teal-600' : 'bg-white text-slate-700 border-slate-200 hover:border-teal-400')}>
                        Sec {s}
                      </button>
                    );
                  })}
                </div>
              </div>
            )}
          </div>
        )}

        {isInterHouse && (
          <div className="md:col-span-12 relative overflow-hidden rounded-2xl border border-purple-200 bg-gradient-to-br from-purple-50/60 to-pink-50/60 p-4">
            <div className="flex items-center gap-2 mb-2">
              <span className="text-[15px]">🏠</span>
              <span className="text-[12.5px] font-extrabold text-slate-900">Pick the two finalist houses</span>
              <span className="text-[10.5px] text-slate-500">tap once for House A, again for House B</span>
            </div>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
              {HOUSES.map((h) => {
                const isA = form.house_a === h.id;
                const isB = form.house_b === h.id;
                const on = isA || isB;
                return (
                  <button
                    key={h.id} type="button"
                    onClick={() => pickHouse(isA ? 'a' : isB ? 'b' : (form.house_a ? 'b' : 'a'), h.id)}
                    className={
                      'group relative flex items-center gap-2 rounded-xl border-2 px-3 py-2.5 text-left transition-all duration-150 ' +
                      (on ? h.tone + ' ring-2 scale-[1.02] shadow-sm border-transparent'
                          : 'bg-white text-slate-700 border-slate-200 hover:border-purple-300 hover:-translate-y-[1px]')
                    }
                  >
                    <span className={'inline-flex h-7 w-7 items-center justify-center rounded-full text-[14px] ' + h.dot + ' text-white shadow-inner'}>{h.icon}</span>
                    <span className="font-bold text-[12.5px]">{h.name}</span>
                    {(isA || isB) && (
                      <span className="ml-auto inline-flex items-center justify-center rounded-md bg-white/70 backdrop-blur text-[10px] font-extrabold px-1.5 py-0.5 border border-white">
                        {isA ? 'A' : 'B'}
                      </span>
                    )}
                  </button>
                );
              })}
            </div>
            {(houseA || houseB) && (
              <div className="mt-3 flex items-center gap-2 text-[12px] font-bold">
                <span className="text-slate-700">Finalists:</span>
                {houseA ? <span className={'inline-flex items-center gap-1 rounded-md border px-2 py-0.5 ' + houseA.tone}><span>{houseA.icon}</span>{houseA.name}</span> : <span className="text-slate-400">House A?</span>}
                <span className="text-slate-400">vs</span>
                {houseB ? <span className={'inline-flex items-center gap-1 rounded-md border px-2 py-0.5 ' + houseB.tone}><span>{houseB.icon}</span>{houseB.name}</span> : <span className="text-slate-400">House B?</span>}
              </div>
            )}
          </div>
        )}

        <label className="md:col-span-12">
          <span className="flex items-center gap-2 text-[10.5px] font-extrabold uppercase tracking-[0.08em] text-slate-500">
            Notes for AI context
            <span className="text-[10px] font-medium normal-case tracking-normal text-slate-400">— guides every review the AI writes</span>
            <button type="button" onClick={magicFillNotes}
              className="ml-auto inline-flex items-center gap-1 rounded-md bg-gradient-to-r from-purple-100 to-pink-100 text-purple-800 hover:from-purple-200 hover:to-pink-200 border border-purple-200 px-2 py-0.5 text-[10px] font-bold normal-case tracking-normal transition"
              title="Auto-fill from event details">
              ✨ Auto-fill with AI
            </button>
          </span>
          <textarea className={inputCls + ' min-h-[68px] resize-y'} value={form.notes} onChange={set('notes')}
                    placeholder="Click ✨ Auto-fill with AI — or write your own themes, judging criteria, special challenges…" />
        </label>

        {error && (
          <div className="md:col-span-12 rounded-xl bg-rose-50 border border-rose-200 px-3 py-2 text-[12px] font-semibold text-rose-700 flex items-center gap-2">
            <span>⚠</span>{error}
          </div>
        )}

        <div className="md:col-span-12 flex items-center justify-between pt-1">
          <p className="text-[11px] text-slate-400">Press <kbd className="rounded border border-slate-300 bg-slate-50 px-1 py-0.5 font-mono text-[10px] font-bold">⏎</kbd> to save</p>
          <button
            type="submit" disabled={saving}
            className="inline-flex items-center gap-2 rounded-xl bg-[linear-gradient(135deg,#4F1FE0,#7C3AED_55%,#EC4899)] px-5 py-2.5 text-[13px] font-bold text-white shadow-[0_8px_24px_-8px_rgba(124,58,237,0.55)] hover:shadow-[0_12px_28px_-8px_rgba(236,72,153,0.6)] hover:-translate-y-[1px] active:scale-[0.98] disabled:opacity-60 transition-all"
          >
            {saving ? <><span className="inline-block animate-spin">◌</span> Saving…</> : <>Continue <span>→</span></>}
          </button>
        </div>
      </div>
    </form>
  );
}

function Pill({ icon, text }) {
  return (
    <span className="inline-flex items-center gap-1 rounded-md bg-slate-50 border border-slate-200 px-2 py-0.5 font-semibold text-slate-700">
      <span aria-hidden>{icon}</span>{text}
    </span>
  );
}
