'use client';

import React, { useState } from 'react';
import { competitionsApi } from '@/lib/competitionsApi';

/**
 * ExportControls
 *  • CSV download (built locally — no server round-trip needed)
 *  • Branded print-to-PDF window
 *  • Save-to-server button (gracefully no-ops if backend route isn't wired)
 */
export default function ExportControls({ competition, results = [] }) {
  const [saving, setSaving] = useState(false);
  const [saved, setSaved] = useState(false);

  function downloadCsv() {
    const rows = [
      ['Student', 'Class', 'Position', 'Points', 'Personal Contribution', 'AI Review'],
      ...results.map((r) => [
        r._student?.full_name || '',
        r._student?.class_name || '',
        r.position || '',
        r.points || 0,
        (r.personal_contribution || '').replace(/\n/g, ' '),
        (r.ai_response || '').replace(/\n/g, ' '),
      ]),
    ];
    const csv = rows.map((row) =>
      row.map((c) => `"${String(c).replace(/"/g, '""')}"`).join(',')
    ).join('\n');
    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${(competition?.name || 'competition').replace(/[^a-z0-9]+/gi, '_')}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  }

  function printPdf() {
    const win = window.open('', '_blank', 'width=900,height=1000');
    if (!win) return;
    const html = `<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(competition?.name || 'Competition')}</title>
      <style>
        @page { margin: 18mm }
        body { font-family: 'Inter', system-ui, -apple-system, sans-serif; color:#0f172a; margin:0; padding:24px; }
        .hero { background:linear-gradient(135deg,#7C3AED,#EC4899); color:#fff; border-radius:18px; padding:24px 28px; margin-bottom:24px; box-shadow:0 10px 30px -10px rgba(124,58,237,.5); }
        .hero h1 { margin:0 0 6px; font-size:28px; letter-spacing:-0.01em; }
        .hero p { margin:0; opacity:.9; font-size:13px; }
        .row { border-bottom:1px solid #e2e8f0; padding:14px 0; page-break-inside:avoid; }
        .row h3 { margin:0; font-size:15px; }
        .meta { color:#64748b; font-size:11px; margin-top:2px; }
        .pos { display:inline-block; padding:2px 8px; border-radius:8px; background:#f1f5f9; font-weight:700; font-size:11px; margin-left:6px; }
        .review { font-family: Georgia, serif; font-size:12.5px; color:#1e293b; margin-top:8px; white-space:pre-wrap; line-height:1.6; }
        .foot { margin-top:32px; font-size:10.5px; color:#94a3b8; text-align:center; }
      </style></head><body>
      <div class="hero">
        <h1>${escapeHtml(competition?.name || '')}</h1>
        <p>${escapeHtml(competition?.date || '')} · ${escapeHtml(competition?.level || '')} · ${escapeHtml(competition?.location || '')}</p>
      </div>
      ${results.map((r) => `
        <div class="row">
          <h3>${escapeHtml(r._student?.full_name || '')}<span class="pos">${escapeHtml(r.position || '—')}</span></h3>
          <div class="meta">${escapeHtml(r._student?.class_name || '')} · ${r.points || 0} pts</div>
          ${r.ai_response ? `<div class="review">${escapeHtml(r.ai_response)}</div>` : ''}
        </div>`).join('')}
      <div class="foot">Generated by Eskoolia · InspireHub</div>
      </body></html>`;
    win.document.write(html);
    win.document.close();
    setTimeout(() => win.print(), 350);
  }

  async function saveToServer() {
    if (!competition?.id || competition._local) return;
    setSaving(true); setSaved(false);
    try {
      await competitionsApi.bulkCreateResults(
        results
          .filter((r) => r.position && !r._student?._demo)
          .map((r) => ({
            competition: competition.id,
            student: r.student_id,
            position: r.position,
            points: r.points,
            personal_contribution: r.personal_contribution,
            performance_notes: '',
            ai_generated: !!r.ai_response,
            ai_response: r.ai_response || '',
          }))
      );
      setSaved(true);
      setTimeout(() => setSaved(false), 2400);
    } catch (e) {
      console.warn('[InspireHub] save failed', e?.message);
    } finally { setSaving(false); }
  }

  return (
    <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-[0_2px_12px_-4px_rgba(15,23,42,0.06)]">
      <div className="flex items-center gap-2 mb-3">
        <span className="inline-flex h-6 w-6 items-center justify-center rounded-md bg-purple-100 text-purple-700 text-[11px] font-extrabold">4</span>
        <h3 className="text-[13.5px] font-extrabold text-slate-900">Export &amp; save</h3>
      </div>
      <div className="flex flex-col gap-2">
        <button onClick={saveToServer} disabled={saving || !competition?.id || competition._local}
          className="inline-flex items-center justify-center gap-1.5 rounded-xl bg-[linear-gradient(135deg,#7C3AED,#EC4899)] px-4 py-2.5 text-[12.5px] font-bold text-white shadow-[0_8px_24px_-8px_rgba(124,58,237,0.55)] hover:shadow-[0_12px_28px_-8px_rgba(236,72,153,0.6)] disabled:opacity-50 disabled:cursor-not-allowed transition-all">
          {saving ? <><span className="inline-block animate-spin">◌</span> Saving…</> : saved ? <>✅ Saved</> : <>💾 Save to server</>}
        </button>
        <button onClick={downloadCsv} className="inline-flex items-center justify-center gap-1.5 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-[12.5px] font-bold text-slate-700 hover:bg-slate-50 transition">
          📊 Download CSV
        </button>
        <button onClick={printPdf} className="inline-flex items-center justify-center gap-1.5 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-[12.5px] font-bold text-slate-700 hover:bg-slate-50 transition">
          🖨 Print as PDF
        </button>
      </div>
      {competition?._local && (
        <p className="mt-3 text-[10.5px] text-amber-700 bg-amber-50 border border-amber-200 rounded-md px-2 py-1.5">
          Server save is disabled while in offline-draft mode.
        </p>
      )}
    </div>
  );
}

function escapeHtml(s = '') {
  return String(s).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
}
