# Generated by Django 6.0.3 on 2026-04-22 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0014_studentcategory_deleted_at_and_more"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentdocument",
            name="file_url",
        ),
        migrations.AddField(
            model_name="studentdocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("birth_certificate", "Birth Certificate"),
                    ("aadhaar_card", "Aadhaar Card"),
                    ("medical_information", "Medical Information"),
                    ("caste_certificate", "Caste Certificate"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="studentdocument",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="student_documents/%Y/%m/"
            ),
        ),
        migrations.AddField(
            model_name="studentdocument",
            name="file_size",
            field=models.PositiveBigIntegerField(
                blank=True, help_text="File size in bytes", null=True
            ),
        ),
        migrations.AddField(
            model_name="studentdocument",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studentdocument",
            name="original_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="studentdocument",
            name="remarks",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="studentdocument",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_documents",
                to="tenancy.school",
            ),
        ),
        migrations.AddField(
            model_name="studentdocument",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="studentdocument",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_documents_uploaded",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="studentdocument",
            name="title",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddIndex(
            model_name="studentdocument",
            index=models.Index(
                fields=["student", "document_type"], name="idx_student_doc_type"
            ),
        ),
        migrations.AddIndex(
            model_name="studentdocument",
            index=models.Index(fields=["school"], name="idx_student_doc_school"),
        ),
    ]
