# Generated by Django 6.0.4 on 2026-04-28 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_normalize_class_names"),
        ("students", "0016_studentgroup_new_fields"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PromotionBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_progress", "In Progress"),
                            ("confirmed", "Confirmed"),
                            ("finalized", "Finalized"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("total_students", models.PositiveIntegerField(default=0)),
                ("promoted_count", models.PositiveIntegerField(default=0)),
                ("retained_count", models.PositiveIntegerField(default=0)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotion_batches",
                        to="core.academicyear",
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promotion_batches_confirmed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promotion_batches_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotion_batches",
                        to="tenancy.school",
                    ),
                ),
                (
                    "target_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_promotion_batches",
                        to="core.academicyear",
                    ),
                ),
            ],
            options={
                "db_table": "promotion_batches",
                "ordering": ["-created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="PromotionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("promote", "Promote"),
                            ("not_promoted", "Not Promoted"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "retention_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("academic", "Academic Performance"),
                            ("attendance", "Attendance"),
                            ("medical", "Medical Leave"),
                            ("behavioral", "Behavioral"),
                            ("parent_request", "Parent Request"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("ai_recommendation", models.TextField(blank=True)),
                ("decision_made_at", models.DateTimeField(blank=True, null=True)),
                ("last_modified_at", models.DateTimeField(auto_now=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="students.promotionbatch",
                    ),
                ),
                (
                    "decision_made_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promotion_record_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "failed_subjects",
                    models.ManyToManyField(
                        blank=True,
                        related_name="failed_promotion_records",
                        to="core.subject",
                    ),
                ),
                (
                    "from_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promotion_records_from_class",
                        to="core.class",
                    ),
                ),
                (
                    "from_section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promotion_records_from_section",
                        to="core.section",
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promotion_record_modifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotion_records",
                        to="students.student",
                    ),
                ),
                (
                    "to_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promotion_records_to_class",
                        to="core.class",
                    ),
                ),
                (
                    "to_section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promotion_records_to_section",
                        to="core.section",
                    ),
                ),
            ],
            options={
                "db_table": "promotion_records",
                "ordering": [
                    "from_class__numeric_order",
                    "from_section__name",
                    "student__roll_no",
                    "student__id",
                ],
            },
        ),
        migrations.CreateModel(
            name="PromotionAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=40)),
                ("details", models.TextField(blank=True)),
                ("ip_address", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promotion_audit_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="students.promotionbatch",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="students.promotionrecord",
                    ),
                ),
            ],
            options={
                "db_table": "promotion_audit_logs",
                "ordering": ["-created_at", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="promotionbatch",
            constraint=models.UniqueConstraint(
                fields=("school", "academic_year"),
                name="uq_promotion_batch_school_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="promotionrecord",
            constraint=models.UniqueConstraint(
                fields=("batch", "student"), name="uq_promotion_record_batch_student"
            ),
        ),
    ]
