# Generated by Django 6.0.4 on 2026-05-04 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_studentdocument_add_consent_form_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrecordaudit',
            name='action',
            field=models.CharField(choices=[('soft_delete', 'Soft Delete'), ('restore', 'Restore'), ('permanent_delete', 'Permanent Delete'), ('update', 'Update')], max_length=20),
        ),
        migrations.CreateModel(
            name='StudentClubMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Member'), ('captain', 'Captain'), ('co_captain', 'Co-Captain'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer')], default='member', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(limit_choices_to={'type': 'CLUB'}, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='students.studentgroup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_memberships', to='students.student')),
            ],
            options={
                'db_table': 'student_club_memberships',
                'ordering': ['club__name', 'student__first_name', 'student__last_name'],
                'constraints': [models.UniqueConstraint(fields=('student', 'club'), name='uq_student_club_membership')],
            },
        ),
    ]
