# Generated by Django 6.0.4 on 2026-05-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0018_studentdocument_add_consent_form_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentrecordaudit",
            name="action",
            field=models.CharField(
                choices=[
                    ("soft_delete", "Soft Delete"),
                    ("restore", "Restore"),
                    ("permanent_delete", "Permanent Delete"),
                    ("update", "Update"),
                ],
                max_length=20,
            ),
        ),
    ]
