# Generated by Django 6.0.4 on 2026-05-04 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0019_alter_studentrecordaudit_action"),
        ("students", "0019_studentclubmembership"),
    ]

    operations = []
