# Generated by Django 5.1.8 on 2026-07-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0022_guardian_user'),
    ]

    operations = [
        # The `middle_name` column already exists in the live `students` table
        # (a pre-existing DB column that had been dropped from the Django
        # model without a matching migration, left NOT NULL with no default —
        # the root cause of every student-enrollment INSERT failing). Only
        # Django's migration state needs to catch up; the database itself was
        # already patched directly (DEFAULT '' added) to unblock enrollment.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='student',
                    name='middle_name',
                    field=models.CharField(blank=True, default='', max_length=80),
                ),
            ],
            database_operations=[],
        ),
    ]
