# Generated by Django 5.1.8 on 2026-07-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0023_student_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubjectassignment',
            name='category',
            field=models.CharField(blank=True, choices=[('first_language', 'First Language'), ('second_language', 'Second Language'), ('third_language', 'Third Language'), ('sport', 'Sports'), ('club', 'Clubs'), ('co_curricular', 'Co-curricular'), ('optional', 'Optional Subjects')], max_length=20),
        ),
    ]
