# Generated by Django 6.0.4 on 2026-05-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0010_command_center'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='admission_a_school__0785b9_idx',
            old_name='admn_audit_school_action_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='admission_a_object__3f16b8_idx',
            old_name='admn_audit_obj_idx',
        ),
        migrations.AlterField(
            model_name='aimessagetemplate',
            name='system_prompt',
            field=models.TextField(default='You are a helpful assistant that writes short, clear, and culturally appropriate messages for Indian school admissions. Produce two variants: Formal and Friendly. Keep messages under 220 characters for SMS/WhatsApp. Use the lead context to personalize.'),
        ),
        migrations.AlterField(
            model_name='aimessagetemplate',
            name='user_prompt_template',
            field=models.TextField(default='Lead context:\n- name: {{lead.name}}\n- child_grade: {{lead.grade_interest}}\n- next_step: {{next_step}}\n- source: {{lead.source}}\n- school_name: {{school.name}}\nGenerate:\n1) Variant A (Formal): ...\n2) Variant B (Friendly): ...\nAlso return the prompt used (redact PII in logs).'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(help_text='e.g. inquiry.create, inquiry.update_status, bulk.send_whatsapp', max_length=80),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='changes',
            field=models.JSONField(default=dict, help_text='Snapshot of changed fields'),
        ),
        migrations.AlterField(
            model_name='bulkjob',
            name='error_detail',
            field=models.JSONField(default=list, help_text='List of {lead_id, error} for failed items'),
        ),
        migrations.AlterField(
            model_name='bulkjob',
            name='payload',
            field=models.JSONField(default=dict, help_text='Extra payload for the action (template_id, text, etc.)'),
        ),
        migrations.AlterField(
            model_name='contactlog',
            name='provider_message_id',
            field=models.CharField(blank=True, help_text='Provider-assigned message/call ID', max_length=255),
        ),
        migrations.AlterField(
            model_name='contactlog',
            name='status',
            field=models.CharField(default='initiated', help_text='initiated, delivered, failed, answered', max_length=32),
        ),
    ]
