# Generated by Django 5.1.8 on 2026-06-05 07:47

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0024_alter_academicyear_board_and_more"),
        ("fees", "0001_initial"),
        ("students", "0021_student_user_link"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("reason", models.TextField(blank=True)),
                ("object_id", models.PositiveIntegerField()),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="FeeAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("due_date", models.DateField()),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Original fee amount at time of assignment",
                        max_digits=12,
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-due_date"],
            },
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("charge", "Fee Charge"),
                            ("payment", "Payment"),
                            ("concession", "Concession"),
                            ("reversal", "Reversal"),
                            ("adjustment", "Adjustment"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Positive for charges, negative for payments/credits",
                        max_digits=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Ledger Entries",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("bank", "Bank Transfer"),
                            ("online", "Online Gateway"),
                            ("wallet", "Wallet"),
                            ("cheque", "Cheque"),
                        ],
                        max_length=20,
                    ),
                ),
                ("paid_at", models.DateTimeField()),
                (
                    "transaction_reference",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-paid_at"],
            },
        ),
        migrations.RemoveField(
            model_name="feesassignment",
            name="academic_year",
        ),
        migrations.RemoveField(
            model_name="feesassignment",
            name="fees_type",
        ),
        migrations.RemoveField(
            model_name="feesassignment",
            name="school",
        ),
        migrations.RemoveField(
            model_name="feesassignment",
            name="student",
        ),
        migrations.RemoveField(
            model_name="feespayment",
            name="assignment",
        ),
        migrations.RemoveField(
            model_name="feespayment",
            name="recorded_by",
        ),
        migrations.RemoveField(
            model_name="feespayment",
            name="school",
        ),
        migrations.RemoveField(
            model_name="feespayment",
            name="student",
        ),
        migrations.RemoveConstraint(
            model_name="feesgroup",
            name="uq_fees_group_school_year_name",
        ),
        migrations.RemoveConstraint(
            model_name="feestype",
            name="uq_fees_type_school_year_group_name",
        ),
        migrations.AlterUniqueTogether(
            name="feesgroup",
            unique_together={("academic_year", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="feestype",
            unique_together={("fees_group", "name")},
        ),
        migrations.AddField(
            model_name="feesgroup",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_fees_groups",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="feestype",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_fee_types",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="feesgroup",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.academicyear"
            ),
        ),
        migrations.AlterField(
            model_name="feesgroup",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="feestype",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.academicyear"
            ),
        ),
        migrations.AlterField(
            model_name="feestype",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="feestype",
            name="fees_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fee_types",
                to="fees.feesgroup",
            ),
        ),
        migrations.AlterField(
            model_name="feestype",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name="feesgroup",
            table=None,
        ),
        migrations.AlterModelTable(
            name="feestype",
            table=None,
        ),
        migrations.AddField(
            model_name="auditevent",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="auditevent",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="feeassignment",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.academicyear"
            ),
        ),
        migrations.AddField(
            model_name="feeassignment",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_fee_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="feeassignment",
            name="fees_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assignments",
                to="fees.feestype",
            ),
        ),
        migrations.AddField(
            model_name="feeassignment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fee_assignments",
                to="students.student",
            ),
        ),
        migrations.AddField(
            model_name="ledgerentry",
            name="assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ledger_entries",
                to="fees.feeassignment",
            ),
        ),
        migrations.AddField(
            model_name="ledgerentry",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_ledger_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ledgerentry",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ledger_entries",
                to="students.student",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="fees.feeassignment",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="collected_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="collected_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fee_payments",
                to="students.student",
            ),
        ),
        migrations.AddField(
            model_name="ledgerentry",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ledger_entries",
                to="fees.payment",
            ),
        ),
        migrations.DeleteModel(
            name="FeesAssignment",
        ),
        migrations.DeleteModel(
            name="FeesPayment",
        ),
        migrations.RemoveField(
            model_name="feesgroup",
            name="school",
        ),
        migrations.RemoveField(
            model_name="feesgroup",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="feestype",
            name="school",
        ),
        migrations.RemoveField(
            model_name="feestype",
            name="updated_at",
        ),
    ]
