# Generated by Django 5.1.8 on 2026-06-05 07:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fees", "0002_auditevent_feeassignment_ledgerentry_payment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feeassignment",
            name="concession_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Concession applied after assignment",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_clearance", "Pending Clearance"),
                    ("pending_reconciliation", "Pending Reconciliation"),
                    ("pending_verification", "Pending Verification"),
                    ("posted", "Posted"),
                    ("bounced", "Bounced"),
                    ("reversed", "Reversed"),
                ],
                default="posted",
                max_length=30,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="feeassignment",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Discount given at time of assignment",
                max_digits=12,
            ),
        ),
    ]
