# Generated by Django 5.1.8 on 2026-06-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fees", "0003_feeassignment_concession_amount_payment_status_and_more"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feesgroup",
            name="applicable_classes",
            field=models.ManyToManyField(blank=True, related_name="fee_groups", to="core.class"),
        ),
    ]
