# Generated by Django 5.1.8 on 2026-06-09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fees", "0004_feesgroup_applicable_classes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="feestype",
            name="default_structure",
            field=models.CharField(
                choices=[
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly"),
                    ("term_wise", "Term-wise"),
                    ("yearly", "Yearly"),
                    ("custom", "Custom"),
                ],
                default="term_wise",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="feestype",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="feestype",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name="deleted_fee_types",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="feestype",
            name="gl_code",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="feestype",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="feestype",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="active",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="feestype",
            name="taxable",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")],
                default="no",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="feestype",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
