# Generated by Django 5.1.5 on 2026-06-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fees", "0006_alter_feestype_unique_together_feeschedule_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feeschedule",
            name="grace_period",
            field=models.PositiveIntegerField(
                default=0, help_text="Grace period in days"
            ),
        ),
        migrations.AddField(
            model_name="feeschedule",
            name="late_fee_rule",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Late fee rule description",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="feeschedule",
            name="term_breakdown",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Array of term-wise amounts and due dates",
            ),
        ),
    ]
