# Generated by Django 5.1.5 on 2026-06-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fees", "0008_concessionrule_latefeerule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concessionrule",
            name="applies_to",
            field=models.CharField(
                help_text="Scope of concession (e.g., Tuition Fee)", max_length=150
            ),
        ),
        migrations.AlterField(
            model_name="concessionrule",
            name="discount_percentage",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="latefeerule",
            name="cap_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="latefeerule",
            name="grace_period_days",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="latefeerule",
            name="penalty_rule",
            field=models.CharField(max_length=255),
        ),
    ]
