# Generated by Django 6.0.4 on 2026-06-16 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_alter_academicyear_board_and_more"),
        ("fees", "0008_concessionrule_latefeerule"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="feeschedule",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="feeschedule",
            name="fee_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="schedules",
                to="fees.feesgroup",
            ),
        ),
        migrations.AddConstraint(
            model_name="feeschedule",
            constraint=models.UniqueConstraint(
                condition=models.Q(("fee_group__isnull", False), ("is_deleted", False)),
                fields=("academic_year", "fee_group", "fee_type"),
                name="unique_schedule_with_group",
            ),
        ),
        migrations.AddConstraint(
            model_name="feeschedule",
            constraint=models.UniqueConstraint(
                condition=models.Q(("fee_group__isnull", True), ("is_deleted", False)),
                fields=("academic_year", "fee_type"),
                name="unique_schedule_without_group",
            ),
        ),
    ]
