# Generated by Django 6.0.4 on 2026-06-18 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0009_alter_concessionrule_applies_to_and_more'),
        ('fees', '0009_alter_feeschedule_unique_together_and_more'),
    ]

    operations = [
    ]
