# Generated by Django 6.0.4 on 2026-06-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0010_merge_20260618_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(blank=True, editable=False, help_text='Auto-generated receipt number in format RCPT-YY-NNNN', max_length=20, null=True, unique=True),
        ),
    ]
