# Generated by Django 6.0.4 on 2026-06-18 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fees", "0011_payment_receipt_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="receipt_number",
        ),
    ]
