# Generated by Django 6.0.4 on 2026-06-18 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0012_remove_payment_receipt_number'),
        ('tenancy', '0018_schooltenant_school_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text='UTR / cheque number / batch ID', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('bank', 'Bank Transfer'), ('online', 'Online / UPI'), ('cheque', 'Cheque'), ('wallet', 'Wallet')], default='bank', max_length=20)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('matched', 'Matched'), ('review', 'Review'), ('needs_mapping', 'Needs Mapping')], default='review', max_length=20)),
                ('match_note', models.TextField(blank=True, help_text='Details of the match or candidate receipt')),
                ('score', models.PositiveSmallIntegerField(default=0, help_text='Confidence score 0-100')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_reconciliations', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='tenancy.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
