# Generated by Django 6.0.4 on 2026-06-19 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0013_add_paymentreconciliation'),
        ('students', '0022_guardian_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentreconciliation',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('online', 'Online / UPI'), ('cheque', 'Cheque'), ('wallet', 'Wallet')], default='bank', max_length=20),
        ),
        migrations.CreateModel(
            name='DueInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('call', 'Phone Call'), ('note', 'Manual Note'), ('reminder', 'Reminder Sent'), ('sms', 'SMS'), ('email', 'Email'), ('resolved', 'Resolved')], default='note', max_length=20)),
                ('note', models.TextField()),
                ('agreed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('agreed_date', models.DateField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='due_interactions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='due_interactions', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
