# Generated by Django 5.1.8 on 2026-07-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0014_add_dueinteraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='collected_by_note',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='payment',
            name='counter',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
