# Generated by Django 5.1.8 on 2026-08-21 07:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_levelscheduleconfig"),
        ("fees", "0015_fix_orphaned_payment_columns"),
        ("students", "0026_student_aadhaar_no_student_abc_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="concessionrule",
            index=models.Index(
                fields=["is_deleted"], name="idx_concessionrule_is_deleted"
            ),
        ),
        migrations.AddIndex(
            model_name="concessionrule",
            index=models.Index(fields=["status"], name="idx_concessionrule_status"),
        ),
        migrations.AddIndex(
            model_name="feeassignment",
            index=models.Index(fields=["due_date"], name="idx_feeassignment_due_date"),
        ),
        migrations.AddIndex(
            model_name="feeschedule",
            index=models.Index(
                fields=["is_deleted"], name="idx_feeschedule_is_deleted"
            ),
        ),
        migrations.AddIndex(
            model_name="feeschedule",
            index=models.Index(fields=["status"], name="idx_feeschedule_status"),
        ),
        migrations.AddIndex(
            model_name="feeschedule",
            index=models.Index(fields=["due_date"], name="idx_feeschedule_due_date"),
        ),
        migrations.AddIndex(
            model_name="feestype",
            index=models.Index(fields=["is_deleted"], name="idx_feestype_is_deleted"),
        ),
        migrations.AddIndex(
            model_name="feestype",
            index=models.Index(fields=["status"], name="idx_feestype_status"),
        ),
        migrations.AddIndex(
            model_name="latefeerule",
            index=models.Index(
                fields=["is_deleted"], name="idx_latefeerule_is_deleted"
            ),
        ),
        migrations.AddIndex(
            model_name="latefeerule",
            index=models.Index(fields=["status"], name="idx_latefeerule_status"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["status"], name="idx_payment_status"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["paid_at"], name="idx_payment_paid_at"),
        ),
    ]
