# Generated by Django 5.1.8 on 2026-07-28 11:18

import apps.settings.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0025_holiday_audience'),
        ('tenancy', '0019_schooltenant_school'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolAttendanceRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_start', models.TimeField(default='09:00')),
                ('shift_end', models.TimeField(default='17:00')),
                ('grace_period_minutes', models.PositiveSmallIntegerField(default=15)),
                ('missing_punch_grace_minutes', models.PositiveSmallIntegerField(default=10)),
                ('min_hours_full_day', models.DecimalField(decimal_places=2, default=8.0, max_digits=4)),
                ('min_hours_half_day', models.DecimalField(decimal_places=2, default=4.0, max_digits=4)),
                ('ot_threshold_hours', models.DecimalField(decimal_places=2, default=9.0, max_digits=4)),
                ('ot_multiplier', models.DecimalField(decimal_places=2, default=1.5, max_digits=4)),
                ('late_marks_per_lop', models.PositiveSmallIntegerField(default=3, help_text='Number of late marks that convert to one LOP deduction; 0 = tracking only')),
                ('lop_deduction_unit', models.CharField(choices=[('full_day', 'Full day'), ('half_day', 'Half day')], default='full_day', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_rules', to='tenancy.school')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'settings_attendance_rules',
            },
        ),
        migrations.CreateModel(
            name='SchoolPolicyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('code_of_conduct', 'Code of Conduct'), ('rulebook', 'Rule Book'), ('norms', 'School Norms'), ('other', 'Other')], default='other', max_length=32)),
                ('file', models.FileField(upload_to='settings/policy_docs/%Y/%m/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveBigIntegerField(default=0, help_text='File size in bytes')),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_documents', to='tenancy.school')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'settings_policy_documents',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['school', 'category'], name='idx_settings_policy_doc_cat')],
            },
        ),
        migrations.CreateModel(
            name='SchoolSMTPSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Label for this config, e.g. 'Primary Gmail relay'", max_length=80)),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(default=587)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('password', apps.settings.fields.EncryptedCharField(blank=True, max_length=512)),
                ('use_tls', models.BooleanField(default=True)),
                ('from_email', models.EmailField(max_length=254)),
                ('sender_name', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smtp_settings', to='tenancy.school')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'settings_smtp_settings',
                'ordering': ['-is_active', 'name'],
                'constraints': [models.UniqueConstraint(fields=('school', 'name'), name='uq_settings_smtp_school_name')],
            },
        ),
        migrations.CreateModel(
            name='SettingsAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='e.g. smtp.activate, leave_policy.update, document.upload', max_length=80)),
                ('object_type', models.CharField(blank=True, max_length=60)),
                ('object_id', models.CharField(blank=True, max_length=60)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings_audit_logs', to='tenancy.school')),
            ],
            options={
                'db_table': 'settings_audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', 'action'], name='settings_au_school__c27188_idx'), models.Index(fields=['object_type', 'object_id'], name='settings_au_object__5afb18_idx')],
            },
        ),
        migrations.CreateModel(
            name='StaffHolidayExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('holiday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_exclusions', to='core.holiday')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_holiday_exclusions', to='tenancy.school')),
            ],
            options={
                'db_table': 'settings_staff_holiday_exclusions',
                'constraints': [models.UniqueConstraint(fields=('school', 'holiday'), name='uq_settings_staff_holiday_exclusion')],
            },
        ),
    ]
