# Generated by Django 5.1.8 on 2026-07-28 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0031_leavetype_allow_backdated_leave_and_more'),
        ('settings', '0001_initial'),
        ('tenancy', '0019_schooltenant_school'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolpolicydocument',
            name='file_type',
            field=models.CharField(blank=True, help_text='Derived display type, e.g. PDF, DOCX', max_length=16),
        ),
        migrations.AddField(
            model_name='schoolsmtpsettings',
            name='bcc_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='schoolsmtpsettings',
            name='priority',
            field=models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('low', 'Low')], default='normal', max_length=16),
        ),
        migrations.AddField(
            model_name='schoolsmtpsettings',
            name='receiver_email_type',
            field=models.CharField(choices=[('email_id', 'Official Email ID'), ('personal_email_id', 'Personal Email ID')], default='email_id', max_length=24),
        ),
        migrations.AddField(
            model_name='schoolsmtpsettings',
            name='smtp_type',
            field=models.CharField(choices=[('local', 'Local'), ('server', 'Server')], default='server', max_length=16),
        ),
        migrations.CreateModel(
            name='CarryForwardLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_year', models.PositiveSmallIntegerField()),
                ('to_year', models.PositiveSmallIntegerField()),
                ('process_mode', models.CharField(choices=[('preview', 'Preview'), ('executed', 'Executed')], default='executed', max_length=16)),
                ('total_processed', models.PositiveIntegerField(default=0)),
                ('total_skipped', models.PositiveIntegerField(default=0)),
                ('total_failed', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carry_forward_logs', to='tenancy.school')),
            ],
            options={
                'db_table': 'settings_carry_forward_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('total_days', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('used_days', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('carried_forward', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('carry_forward_expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='hr.leavetype')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='tenancy.school')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='hr.staff')),
            ],
            options={
                'db_table': 'settings_leave_balances',
            },
        ),
        migrations.CreateModel(
            name='SchoolAttendancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Teaching Staff', 'Non-Teaching Staff'", max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('shift_start', models.TimeField(default='09:00')),
                ('shift_end', models.TimeField(default='17:00')),
                ('grace_period_minutes', models.PositiveSmallIntegerField(default=15)),
                ('missing_punch_grace_minutes', models.PositiveSmallIntegerField(default=10)),
                ('break_duration_minutes', models.PositiveSmallIntegerField(default=30)),
                ('min_hours_full_day', models.DecimalField(decimal_places=2, default=8.0, max_digits=4)),
                ('min_hours_half_day', models.DecimalField(decimal_places=2, default=4.0, max_digits=4)),
                ('early_exit_grace_minutes', models.PositiveSmallIntegerField(default=30)),
                ('ot_threshold_hours', models.DecimalField(decimal_places=2, default=9.0, max_digits=4)),
                ('ot_multiplier_regular', models.DecimalField(decimal_places=2, default=1.5, max_digits=4)),
                ('ot_multiplier_holiday', models.DecimalField(decimal_places=2, default=2.0, max_digits=4)),
                ('late_marks_per_lop', models.PositiveSmallIntegerField(default=3, help_text='Number of late marks that convert to one LOP deduction; 0 = tracking only')),
                ('lop_deduction_unit', models.CharField(choices=[('full_day', 'Full day'), ('half_day', 'Half day')], default='full_day', max_length=16)),
                ('weekly_off_mon', models.BooleanField(default=False)),
                ('weekly_off_tue', models.BooleanField(default=False)),
                ('weekly_off_wed', models.BooleanField(default=False)),
                ('weekly_off_thu', models.BooleanField(default=False)),
                ('weekly_off_fri', models.BooleanField(default=False)),
                ('weekly_off_sat', models.BooleanField(default=True)),
                ('weekly_off_sun', models.BooleanField(default=True)),
                ('absence_alert_enabled', models.BooleanField(default=False)),
                ('absence_alert_after_days', models.PositiveSmallIntegerField(default=3)),
                ('absence_alert_notify_whom', models.CharField(choices=[('manager_and_hr', 'Manager & HR'), ('hr_only', 'HR only'), ('manager_only', 'Manager only')], default='manager_and_hr', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_policies', to='tenancy.school')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'settings_attendance_policies',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.DeleteModel(
            name='SchoolAttendanceRules',
        ),
        migrations.AddIndex(
            model_name='leavebalance',
            index=models.Index(fields=['school', 'year'], name='idx_settings_lb_sch_yr'),
        ),
        migrations.AddConstraint(
            model_name='leavebalance',
            constraint=models.UniqueConstraint(fields=('staff', 'leave_type', 'year'), name='uq_settings_leave_balance'),
        ),
        migrations.AddConstraint(
            model_name='schoolattendancepolicy',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='uq_settings_attendance_policy_name'),
        ),
    ]
