# Generated by Django 5.1.8 on 2026-07-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0014_role_portal_type'),
        ('settings', '0002_schoolpolicydocument_file_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolattendancepolicy',
            name='applies_to_roles',
            field=models.ManyToManyField(blank=True, help_text='Roles this policy applies to. Empty = applies to all staff without a more specific policy.', related_name='attendance_policies', to='access_control.role'),
        ),
    ]
