# Generated by Django 5.1.8 on 2026-07-30 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_schoolattendancepolicy_applies_to_roles'),
        ('tenancy', '0020_schooltenant_country_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentBrandingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_mode', models.CharField(choices=[('generated', 'Generated from school details'), ('uploaded', 'Uploaded letterhead')], default='generated', max_length=16)),
                ('header_style', models.CharField(choices=[('classic', 'Classic'), ('modern', 'Modern'), ('minimal', 'Minimal')], default='classic', max_length=16)),
                ('header_text_color', models.CharField(default='#1A1A2E', help_text='Hex color, e.g. #1A1A2E', max_length=7)),
                ('letterhead_source_file', models.FileField(blank=True, help_text='Original uploaded file (PDF or image), kept for reference/re-download.', null=True, upload_to='settings/branding/letterheads/%Y/%m/')),
                ('letterhead_source_file_type', models.CharField(blank=True, choices=[('pdf', 'PDF'), ('image', 'Image')], max_length=8)),
                ('letterhead_rendered_image', models.ImageField(blank=True, help_text='PNG rasterized from letterhead_source_file — this is what actually gets served.', null=True, upload_to='settings/branding/rendered/%Y/%m/')),
                ('declaration_student_verification', models.TextField(blank=True)),
                ('declaration_staff_onboarding', models.TextField(blank=True)),
                ('declaration_payslip', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_branding', to='tenancy.school')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'settings_document_branding',
            },
        ),
    ]
